### ISSUE TITLE
 Impl with Oracle 19c: exception  ORA-00932: inconsistent datatypes

### ISSUE THREAD

**Issue by chanh2505** [quartznet/quartznet#1047]
**Describe the bug**
I implement Quartz with Oracle and NetCore.
But when I use JobStore and start my application, it threw the exception as below:
```
Quartz.JobPersistenceException
  HResult=0x80131500
  Message=Couldn't store job: ORA-00932: inconsistent datatypes: expected CHAR got BOOLEAN
  Source=Quartz
  StackTrace:
   at Quartz.Impl.AdoJobStore.JobStoreSupport.<StoreJob>d__155.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Quartz.Impl.AdoJobStore.JobStoreSupport.<>c__DisplayClass151_0.<<StoreJobAndTrigger>b__0>d.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Quartz.Impl.AdoJobStore.JobStoreSupport.<ExecuteInNonManagedTXLock>d__268`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Quartz.Impl.AdoJobStore.JobStoreSupport.<ExecuteInNonManagedTXLock>d__268`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Quartz.Impl.AdoJobStore.JobStoreSupport.<StoreJobAndTrigger>d__151.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Quartz.Core.QuartzScheduler.<ScheduleJob>d__82.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at Quartz.Xml.XMLSchedulingDataProcessor.<ScheduleJobs>d__53.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Quartz.ServiceCollectionSchedulerFactory.<GetScheduler>d__5.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Quartz.QuartzHostedService.<StartAsync>d__4.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>d__9.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.<RunAsync>d__4.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.<RunAsync>d__4.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at QuartzUI.Program.Main(String[] args) in D:\Components\QuartzUI\QuartzUI\Program.cs:line 16

  This exception was originally thrown at this call stack:
    [External Code]

Inner Exception 1:
OracleException: ORA-00932: inconsistent datatypes: expected CHAR got BOOLEAN
```

**Version used**

Quartz.AspNetCore (3.2.3)
Quartz.Serialization.Json (3.2.3)
Oracle 19c
NetCore 3.1

**Configure Services**
```
services.AddQuartz(p=> {

                p.SchedulerId = "Test";
                p.SetProperty("quartz.serializer.type", "json");
                p.SetProperty("quartz.jobStore.type", "Quartz.Impl.AdoJobStore.JobStoreTX, Quartz");
                p.SetProperty("quartz.jobStore.driverDelegateType", "Quartz.Impl.AdoJobStore.StdAdoDelegate, Quartz");
                p.SetProperty("quartz.jobStore.tablePrefix", "QRTZ_");
                p.SetProperty("quartz.jobStore.dataSource", "test");
                p.SetProperty("quartz.jobStore.useProperties", "true");
                p.SetProperty("quartz.jobStore.clustered", "true");
                p.SetProperty("quartz.dataSource.test.provider", "OracleODPManaged");
                p.SetProperty("quartz.dataSource.test.connectionString", "User ID=ACH_CHANHTC;Password=Unit#2020;Data Source=(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=192.168.1.32)(PORT=1521)))(CONNECT_DATA=(SID=ORCLACH)));");

                var jobKey = new JobKey("test-key", "custom");

                p.AddJob<TestJob>(j =>
                {
                    j.WithIdentity(jobKey);
                });
                p.AddTrigger(t =>
                {
                    t.ForJob(jobKey);
                    t.WithIdentity("test-trigger", "custom");
                    t.WithCronSchedule("0 0/1 * 1/1 * ? *");
                });

            });
            services.AddQuartzServer(q => q.WaitForJobsToComplete = true); 
```

**Comment by lahma** [comment]
You should use Oracle specific driver delegate. Either by your config style:

```csharp
p.SetProperty("quartz.jobStore.driverDelegateType", typeof(OracleDelegate).AssemblyQualifiedNameWithoutVersion());
```

Or via fluent interface

```csharp
p.UsePersistentStore(store =>
{
    store.UseProperties = true;
    store.UseJsonSerializer();
    store.UseClustering();
    store.UseOracle("my connection string");
});

```
