### ISSUE TITLE
Can't use NpgSql (PostgreSQL) provider via UsePostges method while configuring the PersistentJobStore options

### ISSUE THREAD

**Issue by sjd2021** [quartznet/quartznet#1192]
Issue:

I'm receiving this error message some time after calling `UsePostgres(myConnectionString)` .

> Quartz.SchedulerException: Could not Initialize DataSource: default ---> System.ArgumentException: Error while reading metadata information for provider 'Npgsql' (Parameter 'providerName') ---> Quartz.SchedulerConfigException: Could not parse property 'connectionType' into correct data type: Could not load file or assembly 'Npgsql, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified. ---> System.IO.FileNotFoundException: Could not load file or assembly 'Npgsql, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
    at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, StackCrawlMarkHandle stackMark, ObjectHandleOnStack assemblyLoadContext, Boolean loadTypeFromPartialName, ObjectHandleOnStack type, ObjectHandleOnStack keepalive)
   at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext, Boolean loadTypeFromPartialName)
   at System.RuntimeType.GetType(String typeName, Boolean throwOnError, Boolean ignoreCase, StackCrawlMark& stackMark)
   at System.Type.GetType(String typeName, Boolean throwOnError)
   at Quartz.Util.ObjectUtils.ConvertValueIfNecessary(Type requiredType, Object newValue)
   at Quartz.Util.ObjectUtils.SetPropertyValue(Object target, String propertyName, Object value)
   at Quartz.Util.ObjectUtils.SetObjectProperties(Object obj, NameValueCollection props)
--- End of inner exception stack trace ---
    at Quartz.Util.ObjectUtils.SetObjectProperties(Object obj, NameValueCollection props)
   at Quartz.Impl.AdoJobStore.Common.EmbeddedAssemblyResourceDbMetadataFactory.GetDbMetadata(String providerName)
--- End of inner exception stack trace ---
    at Quartz.Impl.AdoJobStore.Common.EmbeddedAssemblyResourceDbMetadataFactory.GetDbMetadata(String providerName)
   at Quartz.Impl.AdoJobStore.Common.DbProvider.GetDbMetadata(String providerName)
   at Quartz.Impl.AdoJobStore.Common.DbProvider..ctor(String dbProviderName, String connectionString)
   at Quartz.Impl.StdSchedulerFactory.Instantiate()
--- End of inner exception stack trace ---
    at Quartz.Impl.StdSchedulerFactory.Instantiate()
   at Quartz.Impl.StdSchedulerFactory.GetScheduler(CancellationToken cancellationToken)
   at Quartz.ServiceCollectionSchedulerFactory.GetScheduler(CancellationToken cancellationToken)
   at Quartz.QuartzHostedService.StartAsync(CancellationToken cancellationToken)

 This happens while using the latest version of the Quartz nuget packages (below).

Version:

![image](https://user-images.githubusercontent.com/84007094/117775896-f4b64300-b208-11eb-85b6-f3d416d07a8c.png)

Sample:

Here is the code I'm using:

```
                  quartz.UsePersistentStore(p =>
                    {
                        p.UseClustering();
                        quartz.SchedulerId = "AUTO";
                        p.UsePostgres(ConnectionString);
                    });
```

The connection string is valid and works with other tools which communicate with postgres such as entity framework. Here is an example: `"Host=localhost;Database=none;Username=P;Password=P;Search Path=public;Persist Security Info=True"`

**Comment by lahma** [comment]
What is the error message?

**Comment by sjd2021** [comment]
> What is the error message?

My apologies. I submitted this rather late my time. The issue has been updated with the message and stack trace

**Comment by sjd2021** [comment]
That worked. Thank you! 
Is there a page in the documentation which covers which libraries are needed for which plugins? I missed this.
