### ISSUE TITLE
OutOfMemoryException exception.

### ISSUE THREAD

**Issue by jerrylisuzhou** [quartznet/quartznet#1212]
Did anybody get this issue from IJob?     I don't know how to handle it .

System.Threading.Tasks.TaskSchedulerException: An exception was thrown by a TaskScheduler. ---> System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.Threading.Thread.StartInternal(IPrincipal principal, StackCrawlMark& stackMark)
   at System.Threading.Thread.Start(StackCrawlMark& stackMark)
   at System.Threading.Thread.Start(Object parameter)
   at System.Threading.Tasks.ThreadPoolTaskScheduler.QueueTask(Task task)
   at System.Threading.Tasks.Task.ScheduleAndStart(Boolean needsProtection)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ScheduleAndStart(Boolean needsProtection)
   at System.Threading.Tasks.Task.InternalStartNew(Task creatingTask, Delegate action, Object state, CancellationToken cancellationToken, TaskScheduler scheduler, TaskCreationOptions options, InternalTaskOptions internalOptions, StackCrawlMark& stackMark)
   at System.Threading.Tasks.TaskFactory.StartNew(Action action, TaskCreationOptions creationOptions)

Create task like this:

  public override Task Execute(IJobExecutionContext context)
        {
            return Task.Factory.StartNew(() =>
            {
 //other code .
            }, TaskCreationOptions.LongRunning);
        }

**Comment by lahma** [comment]
Why are you creating new task inside the job, the job itself is already a task? W.r.t. out of memory, probably some code of yours and not Quartz's.
