### ISSUE TITLE
System.TypeLoadException: Could not load type when using quartz server .net core

### ISSUE THREAD

**Issue by woldemariam** [quartznet/quartznet#1234]
**Describe the bug**

I am trying to use quartz server with .net core 3.1. However, quartz server is not able to load type. This is not an issue when using .net461

```Configuration Result:
[Success] Name QuartzServer
[Success] DisplayName Quartz Server
[Success] Description Quartz Job Scheduling Server
[Success] ServiceName QuartzServer
Topshelf v4.2.1.215, .NET Framework v3.1.16
2021-06-29 15:16:24,687 [1] INFO  Quartz.Impl.StdSchedulerFactory - Quartz.NET properties loaded from configuration file 'C:\quartz2\Quartz.NET-3.3.0\bin\Release\Quartz.Server\netcoreapp3.1\quartz.config'
2021-06-29 15:16:24,719 [1] WARN  Quartz.Impl.StdSchedulerFactory - RemotingSchedulerExporter configuration was ignored as Remoting is not supported
2021-06-29 15:16:24,728 [1] INFO  Quartz.Core.SchedulerSignalerImpl - Initialized Scheduler Signaller of type: Quartz.Core.SchedulerSignalerImpl
2021-06-29 15:16:24,738 [1] INFO  Quartz.Core.QuartzScheduler - Quartz Scheduler v.3.3.0.0 created.
2021-06-29 15:16:24,740 [1] INFO  Quartz.Plugin.Xml.XMLSchedulingDataProcessorPlugin - Registering Quartz Job Initialization Plug-in.
2021-06-29 15:16:24,741 [1] INFO  Quartz.Simpl.RAMJobStore - RAMJobStore initialized.
2021-06-29 15:16:24,742 [1] INFO  Quartz.Core.QuartzScheduler - Scheduler meta-data: Quartz Scheduler (v3.3.0.0) 'ServerScheduler' with instanceId 'NON_CLUSTERED'
  Scheduler class: 'Quartz.Core.QuartzScheduler' - running locally.
  NOT STARTED.
  Currently in standby mode.
  Number of jobs executed: 0
  Using thread pool 'Quartz.Simpl.DefaultThreadPool' - with 10 threads.
  Using job-store 'Quartz.Simpl.RAMJobStore' - which does not support persistence. and is not clustered.

2021-06-29 15:16:24,743 [1] INFO  Quartz.Impl.StdSchedulerFactory - Quartz scheduler 'ServerScheduler' initialized
2021-06-29 15:16:24,743 [1] INFO  Quartz.Impl.StdSchedulerFactory - Quartz scheduler version: 3.3.0.0
2021-06-29 15:16:24,773 [1] INFO  Quartz.Xml.XMLSchedulingDataProcessor - Parsing XML file: C:\quartz2\Quartz.NET-3.3.0\bin\Release\Quartz.Server\netcoreapp3.1\quartz_jobs.xml with systemId: ~/quartz_jobs.xml
2021-06-29 15:16:24,777 [1] INFO  Quartz.Server.QuartzServer - Scheduler started successfully
The QuartzServer service is now running, press Control+C to exit.
2021-06-29 15:16:24,824 [6] ERROR Quartz.Plugin.Xml.XMLSchedulingDataProcessorPlugin - Could not schedule jobs and triggers from file ~/quartz_jobs.xml: Could not load type 'testQuartJob.SampleJob, testQuartJob'
System.TypeLoadException: Could not load type 'testQuartJob.SampleJob, testQuartJob'
   at Quartz.Simpl.SimpleTypeLoadHelper.LoadType(String name) in /_/src/Quartz/Simpl/SimpleTypeLoadHelper.cs:line 60
   at Quartz.Xml.XMLSchedulingDataProcessor.ProcessInternal(String xml) in /_/src/Quartz/Xml/XMLSchedulingDataProcessor.cs:line 353
   at Quartz.Xml.XMLSchedulingDataProcessor.ProcessFile(String fileName, String systemId, CancellationToken cancellationToken) in /_/src/Quartz/Xml/XMLSchedulingDataProcessor.cs:line 179
   at Quartz.Xml.XMLSchedulingDataProcessor.ProcessFileAndScheduleJobs(String fileName, String systemId, IScheduler sched, CancellationToken cancellationToken) in /_/src/Quartz/Xml/XMLSchedulingDataProcessor.cs:line 679
   at Quartz.Plugin.Xml.XMLSchedulingDataProcessorPlugin.ProcessFile(JobFile jobFile, CancellationToken cancellationToken) in /_/src/Quartz.Plugins/Plugin/Xml/XMLSchedulingDataProcessorPlugin.cs:line 290
2021-06-29 15:16:24,837 [6] INFO  Quartz.Core.QuartzScheduler - Scheduler ServerScheduler_$_NON_CLUSTERED started.
```

**Version used**

quartz server 3.3.2

**To Reproduce**

1. download Quartz.NET-3.3.2.zip from here: https://github.com/quartznet/quartznet/releases/tag/v3.3.2
2. unzip file and navigate to Quartz.NET-3.3.0\bin\Release\Quartz.Server\netcoreapp3.1
3. copy and paste dll into this directory ( i used this one: https://github.com/woldemariam/quartz-my-sample-job/blob/main/bin/release/netcoreapp3.1/testQuartJob.dll) 
4. update quartz_jobs.xml to match type
5. double click on Quartz.Server.exe

**Expected behavior**

Expect it to write to the console "My SampleJob running" and "My SampleJob finished" indefinitely 

**My Code**
My code and type can be found here: https://github.com/woldemariam/quartz-my-sample-job

**Comment by lahma** [comment]
Is this still an issue, usually it's just that dll is misplaced and CLR is unable to load it.

**Comment by lahma** [comment]
Closing as obsolete.
