### ISSUE TITLE
Job execute the Polly retry cause the MySql connection issue

### ISSUE THREAD

**Issue by gaojianzhuang** [quartznet/quartznet#1603]
**Describe the bug**
I used the MySql as the persistent store, this is my configuration as below:
```
builder.Services.AddQuartz(q =>
{
    q.SchedulerId = "Scheduler-Core";

    q.UseMicrosoftDependencyInjectionJobFactory();

    q.UseDefaultThreadPool(tp =>
    {
        tp.MaxConcurrency = 50;
    });
    q.AddJobListener<QuartzJobDbLogger>(EverythingMatcher<JobKey>.AllJobs());
    q.AddSchedulerListener<QuartzJobDbLogger>();

    q.UsePersistentStore(s =>
    {
        s.UseProperties = false;
        s.RetryInterval = TimeSpan.FromSeconds(15);
        s.UseClustering((o) =>
        {
        });
        s.UseMySql(mysql =>
        {
            mysql.ConnectionString = EnvironmentVariables.DbConString;
            mysql.TablePrefix = "QRTZ_";
        });
        s.UseJsonSerializer();
    });

    q.ScheduleJob<MyJob>(trigger => trigger
        .WithIdentity($"{nameof(MyJob)}Trigger")
        .WithCronSchedule(EnvironmentVariables.MyJobCron)
    );
});
builder.Services.AddQuartzServer(options =>
{
    // when shutting down we want jobs to complete gracefully
    options.WaitForJobsToComplete = true;
});
```

**Version used**
Quartz.Net 3.4
Quartz.Net AspNetCore 3.4

**To Reproduce**
In the job execute logic, I use the Polly to execute the retry logic:
```
var delay = Backoff.DecorrelatedJitterBackoffV2(medianFirstRetryDelay: TimeSpan.FromMinutes(5), retryCount: retryTimes);
var policy = Policy.HandleResult<int>(c =>
{
    return c > 0;
}).WaitAndRetryAsync(delay, (handleResult, timespan, retryAttempt, context) =>
{
});
await policy.ExecuteAsync(async () =>
{
    return await RetryMyJobLogic();
});
```
In the "RetryMyJobLogic" method, I have a Dapper to access mySql data. It works fine my local, but in the stage environment, it sometimes throw the exception as below:
```
Parameters: refire = False, unscheduleFiringTrigger = False, unscheduleAllTriggers = False 
  Quartz.JobExecutionException: Job threw an unhandled exception.
  ---> Quartz.SchedulerException: Job threw an unhandled exception.
  ---> System.InvalidOperationException: Connection must be valid and open.
    at MySql.Data.MySqlClient.Interceptors.ExceptionInterceptor.Throw(Exception exception)
    at MySql.Data.MySqlClient.MySqlCommand.CheckState()
    at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
    at System.Data.Common.DbCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
 --- End of stack trace from previous location ---
    at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 418
    at Repository.RetryMyJobRepository.<>c__DisplayClass9_0.<<GetDataByStatusesAsync>b__0>d.MoveNext() in /src/Repository/RetryMyJobRepository.cs:line 191
 --- End of stack trace from previous location ---
    at Repository.RetryMyJobRepository.RetryMyDataAsync(IEnumerable`1 statuses) in /src/Repository/RetryMyJobRepository.cs:line 173
    at JobEngineService.JobEngine.MyJob.RetryMyDataAsync(List`1 vehicleList) in /src/JobEngineService/JobEngine/Jobs/MyJob.cs:line 215
    at JobEngineService.JobEngine.MyJob.<>c__DisplayClass13_0.<<TriggerRetrySyncTrafficViolationDataAsync>b__2>d.MoveNext() in /src/JobEngineService/JobEngine/Jobs/MyJob.cs:line 202
 --- End of stack trace from previous location ---
    at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext)
    at Polly.AsyncPolicy`1.ExecuteAsync(Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
/src/JobEngineService/JobEngine/Jobs/MyJob.cs:line 200
    at JobEngineService.JobEngine.RetryMyJob.Execute(IJobExecutionContext context) in /src/JobEngineService/JobEngine/Jobs/MyJob.cs:line 107
    at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)
    --- End of inner exception stack trace --- [See nested exception: System.InvalidOperationException: Connection must be valid and open.
```

**Expected behavior**
Expecte the job works fine.

**Additional context**
it works fine my local, but in the development environment, sometime it will throw the exception.

I try to remove the Polly retry logic, it works fine. I am not sure whether there are some conflicts between the job and polly.
Anyone can help figure out the root cause ? Thanks so much. :)

**Comment by jafin** [comment]
Where is `RetryMyJobLogic` getting its db connection from?  From reading the stack, are you using the existing quartz connection in that method? If so, perhaps using your own connection obtain/open logic may be more resilient. i.e. not having dependencies on any quartz established connections. (you may not I'm just guessing)

**Comment by gaojianzhuang** [comment]
> Where is `RetryMyJobLogic` getting its db connection from? From reading the stack, are you using the existing quartz connection in that method? If so, perhaps using your own connection obtain/open logic may be more resilient. i.e. not having dependencies on any quartz established connections. (you may not I'm just guessing)

Thanks for your suggestions. RetryMyJobLogic just get the data from the database. The database is MySql, we used the dapper to access.
```
var query = @"SELECT  * from data where status in @statuses ";
using var connection = new MySqlConnection(_connectionString);
{
    connection.Open(); \\ No need, if not the job will throw the connection not open issue.
    var results = await connection.QueryAsync<MyData>(query, new { statuses });
    return results.ToList();
}
```
