### ISSUE TITLE
Fails to recover jobs with .net6 on a Mac M1

### ISSUE THREAD

**Issue by HassanAzzam** [quartznet/quartznet#1712]
**Describe the bug**

On calling `scheduler.Start(token)` server crashes with 
```
Quartz.Impl.AdoJobStore.JobStoreTX Failure occurred during job recovery: Couldn't recover jobs: Incorrect syntax near '0x061c'.
Quartz.JobPersistenceException: Couldn't recover jobs: Incorrect syntax near '0x061c'.
 ---> Microsoft.Data.SqlClient.SqlException (0x80131904): Incorrect syntax near '0x061c'.
   at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__203_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Quartz.Impl.AdoJobStore.StdAdoDelegate.HasMisfiredTriggersInState(ConnectionAndTransactionHolder conn, String state1, DateTimeOffset ts, Int32 count, ICollection`1 resultList, CancellationToken cancellationToken)
   at Quartz.Impl.AdoJobStore.JobStoreSupport.RecoverMisfiredJobs(ConnectionAndTransactionHolder conn, Boolean recovering, CancellationToken cancellationToken)
   at Quartz.Impl.AdoJobStore.JobStoreSupport.RecoverJobs(ConnectionAndTransactionHolder conn, CancellationToken cancellationToken)
ClientConnectionId:381e62da-9f71-410f-8027-f2645fda9a47
Error Number:102,State:1,Class:15
   --- End of inner exception stack trace ---
   at Quartz.Impl.AdoJobStore.JobStoreSupport.RecoverJobs(ConnectionAndTransactionHolder conn, CancellationToken cancellationToken)
   at Quartz.Impl.AdoJobStore.JobStoreSupport.<>c__DisplayClass266_0.<<ExecuteInNonManagedTXLock>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Quartz.Impl.AdoJobStore.JobStoreSupport.ExecuteInNonManagedTXLock[T](String lockName, Func`2 txCallback, Func`3 txValidator, Nullable`1 requestorId, CancellationToken cancellationToken)
   at Quartz.Impl.AdoJobStore.JobStoreSupport.ExecuteInNonManagedTXLock[T](String lockName, Func`2 txCallback, Func`3 txValidator, Nullable`1 requestorId, CancellationToken cancellationToken)
   at Quartz.Impl.AdoJobStore.JobStoreSupport.SchedulerStarted(CancellationToken cancellationToken) [See nested exception: Microsoft.Data.SqlClient.SqlException (0x80131904): Incorrect syntax near '0x061c'.
   at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__203_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Quartz.Impl.AdoJobStore.StdAdoDelegate.HasMisfiredTriggersInState(ConnectionAndTransactionHolder conn, String state1, DateTimeOffset ts, Int32 count, ICollection`1 resultList, CancellationToken cancellationToken)
   at Quartz.Impl.AdoJobStore.JobStoreSupport.RecoverMisfiredJobs(ConnectionAndTransactionHolder conn, Boolean recovering, CancellationToken cancellationToken)
   at Quartz.Impl.AdoJobStore.JobStoreSupport.RecoverJobs(ConnectionAndTransactionHolder conn, CancellationToken cancellationToken)
```

**Version used**

Quartz v3.4.0
.NET v6.0
Azure SQL Edge
OS: MacOSX v12.3.1 ARM x64
Connection string to SQL: Server=localhost;Database=MyDatabase;User Id=sa;Password=MyP@ss

**To Reproduce**

Just running the scheduler on the mentioned environment.

**Expected behavior**

The scheduler to run with no errors

**Additional context**

It works as expected on a Windows machine but not on a Mac M1.

**Comment by lahma** [comment]
I don't have a apple machine so pretty impossible to investigate on my end.

**Comment by lahma** [comment]
Closing, we can consider reopen if someone can provide an environment to debug in.
