### ISSUE TITLE
Missing Tables leads to an odd error.

### ISSUE THREAD

**Issue by drusellers** [quartznet/quartznet#1716]
**Describe the bug**

Running into the db row lock issue I've seen floating around.

After trying a few things, I was able to track down that the tables did not exist in the database that Quartz was expecting. It would be super handy if Quartz would sniff this situation out and then provide a helpful log output that would direct users to the "database provider" specific help documentation that explains the steps to run the required SQL to install the tables.

While I'm making a wish list, it would also be nice to see a metadata type table that tracks the schema version, so that when the app is starting up it can say "You are on database version X, and this library expects version X++".

Let me know if there is any other information that I can provide. 

```
Quartz.Impl.AdoJobStore.LockException: Failure obtaining db row lock: 25P02: current transaction is aborted, commands ignored until end of transaction block
 ---> Npgsql.PostgresException (0x80004005): 25P02: current transaction is aborted, commands ignored until end of transaction block
   at Npgsql.Internal.NpgsqlConnector.<ReadMessage>g__ReadMessageLong|211_0(NpgsqlConnector connector, Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
```

**Version used**

3.4.0.0

**To Reproduce**

https://github.com/drusellers/bugreport-quartz

**Expected behavior**

I would expect either the application to start successfully OR to give some kind of guidance about this error and how to fix it.

A link to documentation would also be great, since this seems to come up from time to time.

**Additional context**

Database Logs

```
endless-aisle-pg-1  | 2022-08-19 16:52:56.852 UTC [34] ERROR:  relation "qrtz_locks" does not exist at character 15
endless-aisle-pg-1  | 2022-08-19 16:52:56.852 UTC [34] STATEMENT:  SELECT * FROM QRTZ_LOCKS WHERE SCHED_NAME = $1 AND LOCK_NAME = $2 FOR UPDATE
endless-aisle-pg-1  | 2022-08-19 16:52:57.865 UTC [34] ERROR:  current transaction is aborted, commands ignored until end of transaction block
``

App Logs
```
[12:02:34 INF] Registering datasource 'default' with db provider: 'Quartz.Impl.AdoJobStore.Common.DbProvider'
[12:02:34 INF] Using object serializer: Quartz.Simpl.JsonObjectSerializer, Quartz.Serialization.Json
[12:02:34 INF] Initialized Scheduler Signaller of type: Quartz.Core.SchedulerSignalerImpl
[12:02:34 INF] Quartz Scheduler created
[12:02:34 INF] JobFactory set to: Quartz.Simpl.MicrosoftDependencyInjectionJobFactory
[12:02:34 INF] Using db table-based data access locking (synchronization).
[12:02:34 INF] JobStoreTX initialized.
[12:02:34 INF] Scheduler meta-data: Quartz Scheduler (v3.4.0.0) 'QuartzScheduler' with instanceId 'NON_CLUSTERED'
  Scheduler class: 'Quartz.Core.QuartzScheduler' - running locally.
  NOT STARTED.
  Currently in standby mode.
  Number of jobs executed: 0
  Using thread pool 'Quartz.Simpl.DefaultThreadPool' - with 40 threads.
  Using job-store 'Quartz.Impl.AdoJobStore.JobStoreTX' - which supports persistence. and is clustered.

[12:02:34 INF] Quartz scheduler 'QuartzScheduler' initialized
[12:02:34 INF] Quartz scheduler version: 3.4.0.0
[12:02:34 INF] Adding 0 jobs, 0 triggers.
[12:02:36 FTL] Endless Aisle encountered an error. Shutting Down
Quartz.Impl.AdoJobStore.LockException: Failure obtaining db row lock: 25P02: current transaction is aborted, commands ignored until end of transaction block
 ---> Npgsql.PostgresException (0x80004005): 25P02: current transaction is aborted, commands ignored until end of transaction block
   at Npgsql.Internal.NpgsqlConnector.<ReadMessage>g__ReadMessageLong|211_0(NpgsqlConnector connector, Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at Quartz.Impl.AdoJobStore.StdRowLockSemaphore.ExecuteSQL(Guid requestorId, ConnectionAndTransactionHolder conn, String lockName, String expandedSql, String expandedInsertSql, CancellationToken cancellationToken)
  Exception data:
    Severity: ERROR
    SqlState: 25P02
    MessageText: current transaction is aborted, commands ignored until end of transaction block
    File: postgres.c
    Line: 1424
    Routine: exec_parse_message
   --- End of inner exception stack trace ---
   at Quartz.Impl.AdoJobStore.StdRowLockSemaphore.ExecuteSQL(Guid requestorId, ConnectionAndTransactionHolder conn, String lockName, String expandedSql, String expandedInsertSql, CancellationToken cancellationToken)
   at Quartz.Impl.AdoJobStore.DBSemaphore.ObtainLock(Guid requestorId, ConnectionAndTransactionHolder conn, String lockName, CancellationToken cancellationToken)
   at Quartz.Impl.AdoJobStore.JobStoreSupport.ExecuteInNonManagedTXLock[T](String lockName, Func`2 txCallback, Func`3 txValidator, Nullable`1 requestorId, CancellationToken cancellationToken)
   at Quartz.Impl.AdoJobStore.JobStoreSupport.ExecuteInNonManagedTXLock[T](String lockName, Func`2 txCallback, Func`3 txValidator, Nullable`1 requestorId, CancellationToken cancellationToken)
   at Quartz.Impl.AdoJobStore.JobStoreSupport.StoreJobAndTrigger(IJobDetail newJob, IOperableTrigger newTrigger, CancellationToken cancellationToken)
   at Quartz.Core.QuartzScheduler.ScheduleJob(IJobDetail jobDetail, ITrigger trigger, CancellationToken cancellationToken)
   at Circa.EndlessAisle.Api.Products.CategorySeedService.StartAsync(CancellationToken cancellationToken) in /Users/drusellers/dev/circa/endless-aisle/src/Circa.EndlessAisle.Api/Products/CategorySeedService.cs:line 32
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Circa.EndlessAisle.Api.Program.Main(String[] args) in /Users/drusellers/dev/circa/endless-aisle/src/Circa.EndlessAisle.Api/Program.cs:line 33 [See nested exception: Npgsql.PostgresException (0x80004005): 25P02: current transaction is aborted, commands ignored until end of transaction block
   at Npgsql.Internal.NpgsqlConnector.<ReadMessage>g__ReadMessageLong|211_0(NpgsqlConnector connector, Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at Quartz.Impl.AdoJobStore.StdRowLockSemaphore.ExecuteSQL(Guid requestorId, ConnectionAndTransactionHolder conn, String lockName, String expandedSql, String expandedInsertSql, CancellationToken cancellationToken)
  Exception data:
    Severity: ERROR
    SqlState: 25P02
    MessageText: current transaction is aborted, commands ignored until end of transaction block
    File: postgres.c
    Line: 1424
    Routine: exec_parse_message]
```

**Comment by lahma** [comment]
I can see the quality of life improvement with proper reporting. Versioning table probably requires v4, but maybe we can try to get some support for detecting invalid schema in v3 too.

**Comment by drusellers** [comment]
Even a check for the tables existing or not (just checking for tables names) would be huge. Since you could link me to a document on the website with additional guidance.

**Comment by lahma** [comment]
There's now database table check during job store initialization, thanks for the detailed report!
