### ISSUE TITLE
Transaction aborted exception using PostgreSQL

### ISSUE THREAD

**Issue by git-heath** [quartznet/quartznet#1786]
**Describe the bug**

When using PostgreSQL in clustering mode, scheduling jobs in parallel exposes a race condition in the `StdRowLockSemaphore` class on the `INSERT` into the `locks` table. This is the case when the `sched_name` does not yet exist in the `locks` table. If two threads execute the `SELECT .... FOR UPDATE` at the same time, they both determine that the row does not exist and therefore both attempt to perform the subsequent `INSERT` in the `locks` table. Only one can succeed, the other will receive a PK violation (error from PostgreSQL):

`ERROR: duplicate key value violates unique constraint "locks_pkey"`

At this point the thread goes into the retry mechanism defined in `StdRowLockSemaphore` but the transaction is already rotten as evinced by the eventual error from PostgreSQL:

`ERROR: current transaction is aborted, commands ignored until end of transaction block`

The exception received in the code is:

```
Quartz.Impl.AdoJobStore.LockException
  HResult=0x80131500
  Message=Failure obtaining db row lock: 25P02: current transaction is aborted, commands ignored until end of transaction block
  Source=Quartz
  StackTrace:
   at Quartz.Impl.AdoJobStore.StdRowLockSemaphore.<ExecuteSQL>d__12.MoveNext()
   at Quartz.Impl.AdoJobStore.DBSemaphore.<ObtainLock>d__12.MoveNext()
   at Quartz.Impl.AdoJobStore.JobStoreSupport.<ExecuteInNonManagedTXLock>d__273`1.MoveNext()
   at Quartz.Impl.AdoJobStore.JobStoreSupport.<ExecuteInNonManagedTXLock>d__273`1.MoveNext()
   at Quartz.Impl.AdoJobStore.JobStoreSupport.<StoreJobAndTrigger>d__156.MoveNext()
   at Quartz.Core.QuartzScheduler.<ScheduleJob>d__82.MoveNext()
   at Program.<>c__DisplayClass0_0.<<<Main>$>b__0>d.MoveNext() in C:\xxx\QuartzAbortedTransaction\QuartzAbortedTransaction\Program.cs:line 37
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()

  This exception was originally thrown at this call stack:
    Npgsql.Internal.NpgsqlConnector.ReadMessage.__ReadMessageLong|215_0(Npgsql.Internal.NpgsqlConnector, bool, Npgsql.Internal.DataRowLoadingMode, bool, bool)
    Npgsql.NpgsqlDataReader.NextResult(bool, bool, System.Threading.CancellationToken)
    Npgsql.NpgsqlCommand.ExecuteReader(System.Data.CommandBehavior, bool, System.Threading.CancellationToken)
    Npgsql.NpgsqlCommand.ExecuteReader(System.Data.CommandBehavior, bool, System.Threading.CancellationToken)
    Npgsql.NpgsqlCommand.ExecuteDbDataReaderAsync(System.Data.CommandBehavior, System.Threading.CancellationToken)
    Quartz.Impl.AdoJobStore.StdRowLockSemaphore.ExecuteSQL(System.Guid, Quartz.Impl.AdoJobStore.ConnectionAndTransactionHolder, string, string, string, System.Threading.CancellationToken)

Inner Exception 1:
PostgresException: 25P02: current transaction is aborted, commands ignored until end of transaction block
```

**Version used**

3.5

**To Reproduce**

The following code uses the `SimpleJob` class defined in the `Quartz.Examples` project (the job itself in unimportant here). A PostgreSQL database is required with all the necessary tables. I use a new name on each run of the sample to force the `INSERT` into the `locks` table every time. The project references the following three packages

```
<PackageReference Include="Quartz" Version="3.5.0" />
<PackageReference Include="Quartz.Serialization.Json" Version="3.5.0" />
<PackageReference Include="Npgsql" Version="6.0.7" />
```

Code to paste in a simple .NET 6 console application (project also added as attachment to this issue).

```
IScheduler sched = await SchedulerBuilder.Create()
        .WithId("instance_one")
        .WithName(Guid.NewGuid().ToString())
        .UseDefaultThreadPool(x => x.MaxConcurrency = 1)
        .UsePersistentStore(x =>
        {
            x.UseProperties = true;
            x.UseClustering();
            x.UsePostgres(apo =>
            {
                apo.ConnectionString = "XXX"; // Replace
                apo.TablePrefix = "XXX"; // Replace
            });
            x.UseJsonSerializer();
        })
        .BuildScheduler();

    string schedId = sched.SchedulerInstanceId;

    Parallel.For(0, 2, async i =>
    {
        IJobDetail job = JobBuilder.Create<SimpleJob>()
            .WithIdentity("job_" + i, schedId) 
            .RequestRecovery()
            .Build();

        ISimpleTrigger trigger = (ISimpleTrigger)TriggerBuilder.Create()
            .WithIdentity("triger_" + i, schedId)
            .StartAt(DateBuilder.FutureDate(1, IntervalUnit.Second))
            .WithSimpleSchedule(x => x.WithRepeatCount(20).WithInterval(TimeSpan.FromSeconds(1)))
            .Build();
        await sched.ScheduleJob(job, trigger); // --> Exception occurs here <--
    });
```

**Expected behavior**

When running in the same process, the `INSERT` to the `locks` table should be thread safe to allow the concurrent scheduling of jobs. 

**Additional context**
Sample project to reproduce problem.
[QuartzAbortedTransaction.zip](https://github.com/quartznet/quartznet/files/9807741/QuartzAbortedTransaction.zip)

**Comment by odel0109** [comment]
Hello @git-heath. Have you found some workaround?
We are expiriencing the same issue with clustered PostgreSQL after upgrading Npgsql from 6.0.6 to 6.0.8 when our service contains multihost connection string. With single host it works fine
