### ISSUE TITLE
SqlException: Invalid column name 'TIME_ZONE_ID' after migrating from v2.5 to v3.4

### ISSUE THREAD

**Issue by acardenaskma** [quartznet/quartznet#1984]
**Describe the bug**

After migrating from System.Data.SqlClient to Microsoft.Data.SqlClient, we had to upgrade our Quartz library from v2.5 to v.3.4.
We ran the DB schema migration scripts from 2.x to 3.x

When trying to schedule an event, we get the following error
```
var scheduledEvent = await Scheduler.ScheduleJob(job, (IReadOnlyCollection<ITrigger>)triggers, true);
```

Quartz.JobPersistenceException
  HResult=0x80131500
  Message=Couldn't store trigger 'DEFAULT.ScheduledTask-3-1' for 'ScheduledTaskJob.3' job: Invalid column name 'TIME_ZONE_ID'.
  Source=Quartz
  StackTrace:
   at Quartz.Impl.AdoJobStore.JobStoreSupport.<StoreTrigger>d__159.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Quartz.Impl.AdoJobStore.JobStoreSupport.<>c__DisplayClass165_0.<<StoreJobsAndTriggers>b__0>d.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Quartz.Impl.AdoJobStore.JobStoreSupport.<>c__DisplayClass262_0.<<ExecuteInLock>b__0>d.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Quartz.Impl.AdoJobStore.JobStoreSupport.<ExecuteInNonManagedTXLock>d__269`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Quartz.Impl.AdoJobStore.JobStoreSupport.<ExecuteInNonManagedTXLock>d__269`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Quartz.Core.QuartzScheduler.<ScheduleJobs>d__88.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Jet.Services.ScheduledEventMain.<ScheduleEvent>d__10`1.MoveNext() in C:\Users\Source\Repos\Services\Main.cs:line 90

Inner Exception 1:
SqlException: Invalid column name 'TIME_ZONE_ID'.

**Version used**
3.4

**quartz properties**
```
                    ["quartz.jobStore.lockHandler.type"] = "Quartz.Impl.AdoJobStore.UpdateLockRowSemaphore, Quartz",
                    ["quartz.jobStore.driverDelegateType"] = "Quartz.Impl.AdoJobStore.SqlServerDelegate, Quartz",
                    ["quartz.jobStore.dataSource"] = "default",
                    ["quartz.dataSource.default.connectionString"] = entities.Database.Connection.ConnectionString,
                    ["quartz.dataSource.default.provider"] = "MicrosoftDataSqlClient",
                    ["quartz.jobStore.type"] = "Quartz.Impl.AdoJobStore.JobStoreTX, Quartz",
                    ["quartz.jobStore.useProperties"] = "true",
                    ["quartz.jobStore.tablePrefix"] = "QRTZ_",
   		    ["quartz.serializer.type"] = "json"
```

**Comment by jafin** [comment]
Yep looks like it may of been missed.

the 2.5 to 2.6 SQL scripts shows :

```sql
alter table QRTZ_SIMPROP_TRIGGERS add TIME_ZONE_ID [NVARCHAR] (80);
```

but you also might need the following (quick glance)

```sql
alter table [QRTZ_CRON_TRIGGERS] add TIME_ZONE_ID [NVARCHAR] (80);
```

**Comment by acardenaskma** [comment]
Thanks! @jafin 
That was it. I missed that schema update from 2.5. to 2.6. 
I saw the one from table QRTZ_CRON_TRIGGERS and I mixed them up.

I appreciate the quick response.
Alain.
