### ISSUE TITLE
CronExpression.GetNextValidTimeAfter NullReferenceException when JSON Deserialized.

### ISSUE THREAD

**Issue by JimGrinwald** [quartznet/quartznet#1996]
**Describe the bug**

A contract with a CronExpression property serialized to JSON and stored (forexample using Azure storage), then dezerialized, will throw NullReferenceException when GetNextValidTimeAfter is called.

**Version used**

3.6.2

**To Reproduce**

- Create a CronExpression instance with a valid cron string.
- Call GetNextValidTimeAfter on the created.
- Serialize to JSON, deserialize JSON to new CronExpression instance.
- Call GetNextValidTimeAfter on the new instance.

**Expected behavior**

Expectation would be for GetNextValidTimeAfter to not throw exception, instead return proper data.

**Additional context**

**Comment by lahma** [comment]
Would you like to offer a PR to improve things?

**Comment by jafin** [comment]
@JimGrinwald  can you provide the the way you are deserializing and the  cron statement.  I ran a quick test and it appears to return ok or I'm missing something in the test perhaps.
 
Tested against 3.6.2 and 4.x 

```csharp
  [Test]
        public void CanGetNextTimeAfterSerialized()
        {
            CronExpression cronExpression = new CronExpression("0 15 23 * * ?");

            DateTimeOffset cal = new DateTime(2005, 6, 1, 23, 16, 0).ToUniversalTime();
            DateTimeOffset nextExpectedFireTime = new DateTime(2005, 6, 2, 23, 15, 0).ToUniversalTime();
            Assert.AreEqual(nextExpectedFireTime, cronExpression.GetNextValidTimeAfter(cal).Value);
            var serial = base.serializer.Serialize(cronExpression);
            var deSerializedCron = base.serializer.DeSerialize<CronExpression>(serial);
            Assert.AreEqual(nextExpectedFireTime, deSerializedCron.GetNextValidTimeAfter(cal).Value);
        }
```

![image](https://user-images.githubusercontent.com/127927/229250520-50fe54a4-2e2f-4d3a-b661-fe369b5028e8.png)

**Comment by jafin** [comment]
Ok I just tried a basic Newtonsoft Json Serializer and can get an exception. (3.6.2 /4.x)
I'll take a quick look see if I can offer a PR.

```csharp
  [Test]
        public void CanGetNextTimeAfterJsonSerialized()
        {
            CronExpression cronExpression = new CronExpression("0 15 23 * * ?");

            DateTimeOffset cal = new DateTime(2005, 6, 1, 23, 16, 0).ToUniversalTime();
            DateTimeOffset nextExpectedFireTime = new DateTime(2005, 6, 2, 23, 15, 0).ToUniversalTime();
            Assert.AreEqual(nextExpectedFireTime, cronExpression.GetNextValidTimeAfter(cal).Value);
            var jsonCron = JsonConvert.SerializeObject(cronExpression);
            var deSerializedCron = JsonConvert.DeserializeObject<CronExpression>(jsonCron);
            Assert.AreEqual(nextExpectedFireTime, deSerializedCron.GetNextValidTimeAfter(cal).Value);
        }
```

```shell

System.NullReferenceException : Object reference not set to an instance of an object.
   at Quartz.Util.SortedSetExtensions.TailSet(SortedSet`1 set, Int32 value) in D:\Data\_CodeOS\quartznet\src\Quartz\Util\SortedSetExtensions.cs:line 10
   at Quartz.CronExpression.GetTimeAfter(DateTimeOffset afterTimeUtc) in D:\Data\_CodeOS\quartznet\src\Quartz\CronExpression.cs:line 1646
   at Quartz.CronExpression.GetNextValidTimeAfter(DateTimeOffset date) in D:\Data\_CodeOS\quartznet\src\Quartz\CronExpression.cs:line 478
   at Quartz.Tests.Unit.CronExpressionTest.CanGetNextTimeAfterJsonSerialized() in D:\Data\_CodeOS\quartznet\src\Quartz.Tests.Unit\CronExpressionTest.cs:line 175

```

**Comment by jafin** [comment]
Ok should be a simple fix.

```csharp

  protected CronExpression(SerializationInfo info, StreamingContext context)
        {
            var version = GetVersion(info);
            switch (version)
            {
                case 0:
                    CronExpressionString = info.GetValue<string>("cronExpressionString")!;
                    TimeZone = info.GetValue<TimeZoneInfo>("timeZone")!;
                    break;
                case 1:
                    CronExpressionString = info.GetValue<string>("cronExpression")!;
                    var timeZoneId = info.GetValue<string>("timeZoneId")!;
                    if (!string.IsNullOrEmpty(timeZoneId))
                    {
                        timeZone = TimeZoneUtil.FindTimeZoneById(timeZoneId);
                    }
                    
                    break;
                default:
                    ThrowHelper.ThrowNotSupportedException($"Unknown serialization version {version}");
                    break;
            }
            BuildExpression(CronExpressionString); //*** NEW CODE ****
        }

**Comment by jafin** [comment]
@JimGrinwald I raised a PR for this, but it was a breaking change (removing interface on CronExpression), so targeted v4.x
