### ISSUE TITLE
Example 12_RemoteClientServerJobScheduling is not working due to preprocessor flag that not enabled in the package

### ISSUE THREAD

**Issue by gileli121** [quartznet/quartznet#2016]
**Describe the bug**

We get the following error on following this example:
https://github.com/quartznet/quartznet/tree/main/src/Quartz.Examples/12_RemoteClientServerJobScheduling 

```
PS C:\Users\Gil\Desktop\learn quartz.net\QuartznetWorker> dotnet run
Building...
Unhandled exception. Quartz.SchedulerException: Error communicating with remote scheduler.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Quartz.Impl.RemoteScheduler.<>c.<get_SchedulerName>b__7_0(IRemotableQuartzScheduler x)
   at Quartz.Impl.RemoteScheduler.ReadPropertyInGuard[T](Func`2 action)
   --- End of inner exception stack trace ---
   at Quartz.Impl.RemoteScheduler.ReadPropertyInGuard[T](Func`2 action)
   at Quartz.Impl.RemoteScheduler.get_SchedulerName()
   at Quartz.Impl.SchedulerRepository.Bind(IScheduler sched)
   at Quartz.Impl.StdSchedulerFactory.GetScheduler(CancellationToken cancellationToken)
   at Program.<Main>$(String[] args) in C:\Users\Gil\Desktop\learn quartz.net\QuartznetWorker\Program.cs:line 7
   at Program.<Main>(String[] args) [See nested exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Quartz.Impl.RemoteScheduler.<>c.<get_SchedulerName>b__7_0(IRemotableQuartzScheduler x)
   at Quartz.Impl.RemoteScheduler.ReadPropertyInGuard[T](Func`2 action)]
```

`QuartznetWorker.cs` is code that mostly copied from 
https://github.com/quartznet/quartznet/blob/main/src/Quartz.Examples/12_RemoteClientServerJobScheduling/RemoteClientExample.cs
And it crash on:
```c#
            IScheduler sched = await SchedulerBuilder.Create()
                .WithName("RemoteClient")
                .UseDefaultThreadPool(x => x.MaxConcurrency = 5)
                .ProxyToRemoteScheduler("tcp://127.0.0.1:555/QuartzScheduler")
                .BuildScheduler();

```

It executed while the host program had already created a Scheduler on 127.0.0.1:555 (or at least not crashed...)

I already found the source of the issue. See under the Additional context section.

**Version used**
3.6.2

With which version did you encounter this behavior.
3.6.2

**To Reproduce**

Before you start, set up a Redis server on localhost (same computer where you run it), port 6379, and password `ABCD1234` (or you will need to update the code with the correct port and password)

According to my most recent understanding, Redis is probably not required to reproduce it. Ram job storage may work here also.
I don't have time to make a more isolated scenario.
I report my findings using my most recent code without additional changes to the code that was used to reproduce it.

To reproduce

1. Download and unzip the following project:
[learn quartz.net.zip](https://github.com/quartznet/quartznet/files/11340476/learn.quartz.net.zip)

2. Run the command `dotnet run` under the `QuartznetProducer` folder. Note that the Redis server should run on the same port and password your Redis server uses.
2.1. Verify that QuartznetProducer is working: Go to http://localhost:5225/quartz/Jobs, and you should see a dashboard.
![image](https://user-images.githubusercontent.com/17680514/234786018-7ba3a183-bc8e-4466-91e8-d4c696f2c89d.png)
2.2. Verify that QuartznetProducer is working: Go to: http://localhost:5225/swagger/index.html and you should see the following: 
![image](https://user-images.githubusercontent.com/17680514/234786247-2ed2f80f-da94-4c29-94b7-33b7e2bd0263.png)
3. Send POST request to `http://localhost:5225/QuartznetProducer/Test1` via swagger or use command:
```
curl -X 'POST' \
  'http://localhost:5225/QuartznetProducer/Test1' \
  -H 'accept: */*' \
  -d ''
```
3.1 Verify that it is working: Go to http://localhost:5225/quartz/Jobs, and you should see:
![image](https://user-images.githubusercontent.com/17680514/234786698-240d9a9f-a59b-43a5-a7ac-2fed13c66970.png)
3.2 Verify it is working: Stop the QuartznetProducer process and start it again. After that, go to http://localhost:5225/quartz/Job . You should see the job. This proves by 100% that that data is stored in Redis (otherwise, you won't see it after restart)
4. Run the command `dotnet run` on `QuartznetWorker` folder 

**Expected behavior**
The code from `QuartznetWorker` should be able to build the `IScheduler` object (even if I don't use it yet.. I stop to continue to write it because this basic part fails)
Instead, you got the error that I showed above.

**Additional context**

After a lot of investigation and debugging the internal code of this repo, I found out that the misleading error `Error communicating with remote scheduler` was caused on the code:
```c#
IScheduler scheduler = await SchedulerBuilder.Create()
    .WithName("RemoteClient")
    .UseDefaultThreadPool(x => x.MaxConcurrency = 5)
    .ProxyToRemoteScheduler("tcp://127.0.0.1:555/QuartzScheduler")
    .BuildScheduler();

```
Was originated from `.BuildScheduler()` part.
`.BuildScheduler()` method. at some point, it executed this method:
https://github.com/quartznet/quartznet/blob/98653375cdc1861b4b98719ce6471c7e632f2490/src/Quartz/Impl/StdSchedulerFactory.cs#L1093 

For some reason, when debugging it, I found this line:
![image](https://user-images.githubusercontent.com/17680514/234790397-03a5a8c9-be7b-492d-97dc-e70602f3b155.png)
But it is missing on the link (and not even in the main branch).
Anyway, line `SchedulerRepository.Instance.Bind(sched);` executes this code:
![image](https://user-images.githubusercontent.com/17680514/234790875-5284350e-d557-4d2d-a066-fc2d8513ccf5.png)

The exception triggered from the property `SchedulerName`.
It turns out that when it reads this property, it triggers the following:
```c#
        public virtual string SchedulerName
        {
            get { return ReadPropertyInGuard(x => x.SchedulerName); }
        }
``` 
from `RemoteScheduler.cs` 
That triggers `protected virtual T ReadPropertyInGuard<T>(Func<IRemotableQuartzScheduler, T> action)` that triggers `protected virtual IRemotableQuartzScheduler GetRemoteScheduler()` that triggers `rsched = proxyFactory.GetProxy();` until we get to `public IRemotableQuartzScheduler? GetProxy()` from here https://github.com/quartznet/quartznet/blob/98653375cdc1861b4b98719ce6471c7e632f2490/src/Quartz/Simpl/RemotingSchedulerProxyFactory.cs#L20 

Then, there is the weird part about your preprocessor... no Idea why you did it.
Anyway, that preprocessor is undefined, and I have no idea how to define it because I don't build this nuget myself. So because the preprocessor is undefined, it returns null.
![image](https://user-images.githubusercontent.com/17680514/234792385-dbfb507b-bf32-4ee1-ba00-abf7e24dcb82.png)

Further investigating gives some clue that, for some reason, you enable it only when it is built using net472 
![image](https://user-images.githubusercontent.com/17680514/234792700-55caa7c7-e4a4-4b43-b306-5ee6df2e11e5.png)
https://github.com/quartznet/quartznet/blob/28b5faec68aa7f3227b3e744780617ada0f0eb6f/src/Directory.Build.props#L54
Why? No idea.. You did it.. 

I guess that if I try to do the whole process and get it somehow to build, it may work.
But I don't have so much time for it, and it took me a long time to figure it out.

Please help and fix this bug or enable this feature in recent dotnet.

Thank you.

**Comment by lahma** [comment]
Closing as stale — this was related to the remoting/preprocessor flag setup in Example 12, which has since been de-emphasized. If this is still relevant on a current version, please open a new issue with reproduction steps.
