### ISSUE TITLE
Support for TransactionScope to include the scheduling in an existing transaction

### ISSUE THREAD

**Issue by NilsEngelbach** [quartznet/quartznet#2038]
**Is your feature request related to a problem? Please describe.**
I want to schedule jobs within a transaction using the `TransactionScope`:

```c#
// Not working: Making changes and add job in same transaction
public async Task ExampleMethod()
{
    using (var transaction = new TransactionScope(TransactionScopeAsyncFlowOption.Enabled))
    {
        // Make changes to entities
        var entity = _dbContext.ExampleEntities.Add(new ExampleEntity() { Name = new Random().Next(1, 100).ToString() });
        await _dbContext.SaveChangesAsync();

        // Add job for entity
        var scheduler = await _schedulerFactory.GetScheduler();
        var job = JobBuilder.Create<ExampleJob>()
            .WithIdentity("exampleJob")
            .UsingJobData("entity-name", entity.Entity.Name)
            .Build();
        var trigger = TriggerBuilder.Create()
            .WithIdentity("exampleTrigger")
            .StartNow()
            .Build();
        await scheduler.ScheduleJob(job, trigger);

        transaction.Complete();
    }
}
```

This gives the following exception:
```
System.InvalidOperationException: A transaction is already in progress; nested/concurrent transactions aren't supported.
   at Npgsql.NpgsqlConnection.BeginTransaction(IsolationLevel level, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlConnection.BeginTransaction(IsolationLevel level)
   at Npgsql.NpgsqlConnection.BeginDbTransaction(IsolationLevel isolationLevel)
   at Quartz.Impl.AdoJobStore.JobStoreSupport.GetConnection()
```

It can be fixed by suppressing the `TransactionScope` or removing it, but this is not the wanted behavior because everything including the scheduling schould be done in the transaction:
```c#
// This is working - but not same transaction
public async Task ExampleMethodWithWorkaround()
{
    using (var transaction = new TransactionScope(TransactionScopeAsyncFlowOption.Enabled))
    {
        // Make changes to entities
        var entity = _dbContext.ExampleEntities.Add(new ExampleEntity() { Name = new Random().Next(1, 100).ToString() });
        await _dbContext.SaveChangesAsync();

        // Add job for entity
        var scheduler = await _schedulerFactory.GetScheduler();
        var job = JobBuilder.Create<ExampleJob>()
            .WithIdentity("exampleJob")
            .UsingJobData("entity-name", entity.Entity.Name)
            .Build();
        var trigger = TriggerBuilder.Create()
            .WithIdentity("exampleTrigger")
            .StartNow()
            .Build();
        
        using (var suppressedTransactionScope = new TransactionScope(TransactionScopeOption.Suppress, TransactionScopeAsyncFlowOption.Enabled))
        {
            await scheduler.ScheduleJob(job, trigger);
        }

        transaction.Complete();
    }
}

// This is working - but not same transaction
public async Task ExampleMethodWithoutScope()
{
    // Make changes to entities
    var entity = _dbContext.ExampleEntities.Add(new ExampleEntity() { Name = new Random().Next(1, 100).ToString() });
    await _dbContext.SaveChangesAsync();

    // Add job for entity
    var scheduler = await _schedulerFactory.GetScheduler();
    var job = JobBuilder.Create<ExampleJob>()
        .WithIdentity("exampleJob")
        .UsingJobData("entity-name", entity.Entity.Name)
        .Build();
    var trigger = TriggerBuilder.Create()
        .WithIdentity("exampleTrigger")
        .StartNow()
        .Build();
    await scheduler.ScheduleJob(job, trigger);
}
```

The complete example can be found here: https://github.com/NilsEngelbach/quartznet-transactionscope-example/blob/main/Source/TransactionScopeExample/ExampleService.cs

**Describe the solution you'd like**
I also saw that in the Quartz Java Implementation there is the Option to use the `JobStoreCMT` where the transaction is also managed outside of Quartz.
How could this feature be implemented in Quartz.NET? I would also love to contribute the feature, but i don't really know where to start and there are any special things to consider?

**Comment by lahma** [comment]
We have custom `JobStoreCMT` already, which [is being used in Spring.NET](https://github.com/spring-projects/spring-net/blob/2d5c33acee262f111099f30d1efdfce4a1b3a5c7/src/Spring/Spring.Scheduling.Quartz3/Scheduling/Quartz/LocalDataSourceJobStore.cs#L26)  so not sure if it helps with your use case, but it should be there.

**Comment by NilsEngelbach** [comment]
@lahma Thanks for the quick response and the hint.

I implemented a JobStore for the EntityFramework DbContext accordingly:

```c#
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Storage;
using Quartz.Impl.AdoJobStore;
using Quartz.Util;

namespace TransactionScopeExample;

public interface IExampleDbContextJobStore {};

public class ExampleDbContextJobStore : DbContextJobStore<ExampleDbContext>, IExampleDbContextJobStore
{
    public ExampleDbContextJobStore(ExampleDbContext dbContext) : base(dbContext)
    {
    }
}

/// <summary>
/// Subclass of Quartz's JobStoreCMT class that delegates to a Entity Framework managed
/// DbContext instead of using a Quartz-managed connection pool.
/// </summary>
/// <remarks>
/// <p>Operations performed by this JobStore will properly participate in any
/// kind of TransactionScoped transaction, as it uses Entity Frameworks Database
/// Connection handling methods that are aware of a current transaction.</p>
///
/// <p>Note that all Quartz Scheduler operations that affect the persistent
/// job store should usually be performed within active transactions,
/// as they assume to get proper locks etc.</p>
/// </remarks>
public class DbContextJobStore<T> : JobStoreCMT where T : DbContext
{
    private readonly T _dbContext;

    public DbContextJobStore(T dbContext)
    {
        _dbContext = dbContext;
    }

    public override string InstanceName
    {
        get => base.InstanceName;
        set
        {
            base.InstanceName = value;
            DBConnectionManager.Instance.AddConnectionProvider(InstanceName, new DbContextProviderAdapter(_dbContext));
        }
    }

    protected override ConnectionAndTransactionHolder GetNonManagedTXConnection()
    {
        var dbConnection = _dbContext.Database.GetDbConnection();
        var transaction = _dbContext.Database.CurrentTransaction;
        return new ConnectionAndTransactionHolder(dbConnection, transaction?.GetDbTransaction());
    }

    protected override void CloseConnection(ConnectionAndTransactionHolder connectionAndTransactionHolder)
    {
        connectionAndTransactionHolder.Connection.Close();
    }
}
```

But when i try to configure it with:
```c#
c.Properties.Add("quartz.jobStore.type", "TransactionScopeExample.IExampleDbContextJobStore");
```
It always throws an Exception: `'The given assembly name was invalid.'`

```c#
builder.Services.AddQuartz(q =>
{
    q.UseMicrosoftDependencyInjectionScopedJobFactory();

    q.UsePersistentStore(c =>
    {
        c.Properties.Add("quartz.jobStore.type", "TransactionScopeExample.IExampleDbContextJobStore");
        c.UseProperties = true;
        c.UseJsonSerializer();
        c.UsePostgres(b => {
            b.UseDriverDelegate<PostgreSQLDelegate>();
            b.ConnectionString = ExampleDbContext.ConnectionString;
            b.TablePrefix = "quartz.qrtz_";
        });
    });
});
```

```
An unhandled exception of type 'System.IO.FileLoadException' occurred in System.Private.CoreLib.dll: 'The given assembly name was invalid.'
   at System.Reflection.AssemblyNameParser.ThrowInvalidAssemblyName()
   at System.Reflection.AssemblyNameParser.Parse()
   at System.Reflection.AssemblyName.ParseAsAssemblySpec(Char* pAssemblyName, Void* pAssemblySpec)
   at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, StackCrawlMarkHandle stackMark, ObjectHandleOnStack assemblyLoadContext, ObjectHandleOnStack type, ObjectHandleOnStack keepalive)
   at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext)
   at System.Type.GetType(String typeName, Boolean throwOnError)
   at Quartz.Simpl.SimpleTypeLoadHelper.LoadType(String name)
   at Quartz.Impl.StdSchedulerFactory.<Instantiate>d__65.MoveNext()
   at Quartz.Impl.StdSchedulerFactory.<GetScheduler>d__71.MoveNext()
   at Quartz.ServiceCollectionSchedulerFactory.<GetScheduler>d__6.MoveNext()
   at Quartz.QuartzHostedService.<StartAsync>d__7.MoveNext()
   at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>d__12.MoveNext()
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.<RunAsync>d__4.MoveNext()
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.<RunAsync>d__4.MoveNext()
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at Program.<Main>$(String[] args) in Program.cs:line 44
```

**Comment by NilsEngelbach** [comment]
@lahma Thank you for the quick response and the hint.

I implemented a JobStore for the EntityFramework DbContext:

```c#
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Storage;
using Quartz.Impl.AdoJobStore;
using Quartz.Util;

namespace TransactionScopeExample;


public class ExampleDbContextJobStore : DbContextJobStore<ExampleDbContext>
{
    public ExampleDbContextJobStore(ExampleDbContext dbContext) : base(dbContext){ }
}

/// <summary>
/// Subclass of Quartz's JobStoreCMT class that delegates to a Entity Framework managed
/// DbContext instead of using a Quartz-managed connection pool.
/// </summary>
/// <remarks>
/// <p>Operations performed by this JobStore will properly participate in any
/// kind of TransactionScoped transaction, as it uses Entity Frameworks Database
/// Connection handling methods that are aware of a current transaction.</p>
///
/// <p>Note that all Quartz Scheduler operations that affect the persistent
/// job store should usually be performed within active transactions,
/// as they assume to get proper locks etc.</p>
/// </remarks>
public class DbContextJobStore<T> : JobStoreCMT where T : DbContext
{
    private readonly T _dbContext;

    public DbContextJobStore(T dbContext)
    {
        _dbContext = dbContext;
    }

    public override string InstanceName
    {
        get => base.InstanceName;
        set
        {
            base.InstanceName = value;
            DBConnectionManager.Instance.AddConnectionProvider(InstanceName, new DbContextProviderAdapter(_dbContext));
        }
    }

    protected override ConnectionAndTransactionHolder GetNonManagedTXConnection()
    {
        var dbConnection = _dbContext.Database.GetDbConnection();
        var transaction = _dbContext.Database.CurrentTransaction;
        return new ConnectionAndTransactionHolder(dbConnection, transaction?.GetDbTransaction());
    }

    protected override void CloseConnection(ConnectionAndTransactionHolder connectionAndTransactionHolder)
    {
        connectionAndTransactionHolder.Connection.Close();
    }
}
```

```c#
builder.Services.AddScoped<ExampleDbContextJobStore>();

builder.Services.AddQuartz(q =>
{
    q.UseMicrosoftDependencyInjectionJobFactory();

    q.UsePersistentStore(c =>
    {
        c.Properties.Set("quartz.jobStore.type", "TransactionScopeExample.ExampleDbContextJobStore, TransactionScopeExample");
        c.UseProperties = true;
        c.UseJsonSerializer();
        c.UsePostgres(b => {
            b.UseDriverDelegate<PostgreSQLDelegate>();
            b.ConnectionString = ExampleDbContext.ConnectionString;
            b.TablePrefix = "quartz.qrtz_";
        });
    });
});
```

But now i need an emtpy constructor. Do you have any Idea how I could use the Dependency Injection?

```
An unhandled exception of type 'Quartz.SchedulerException' occurred in System.Private.CoreLib.dll: 'JobStore of type 'TransactionScopeExample.ExampleDbContextJobStore' could not be instantiated.'
 Inner exceptions found, see $exception in variables window for more details.
 Innermost exception 	 System.ArgumentException : Cannot instantiate type which has no empty constructor (Parameter 'ExampleDbContextJobStore')
   at Quartz.ExceptionHelper.ThrowArgumentException(String message, String paramName)
   at Quartz.Util.ObjectUtils.InstantiateType[T](Type type)
   at Quartz.ServiceCollectionSchedulerFactory.InstantiateType[T](Type implementationType)
   at Quartz.Impl.StdSchedulerFactory.<Instantiate>d__65.MoveNext()
```

**Comment by NilsEngelbach** [comment]
So the problem is using a custom `scoped` `JobStore` that relies on the Dependency Injection in the constructor:
- `var service = serviceProvider.GetService<T>();` will not resolve the scoped service
- `service = ObjectUtils.InstantiateType<T>(implementationType);` requires type with empty constructor

```c#
internal sealed class ServiceCollectionSchedulerFactory : StdSchedulerFactory
{
    protected override T InstantiateType<T>(Type? implementationType)
    {
        var service = serviceProvider.GetService<T>(); // Can not resolve scoped services!
        if (service is null)
        {
            service = ObjectUtils.InstantiateType<T>(implementationType); // Requires type with empty constructor
        }
        return service;
    }
}
```

Maybe a custom `ServiceCollectionSchedulerFactory` that creates an `Scope` similar to the `MicrosoftDependencyInjectionJobFactory` for `JobFactory` would help? Or how could this be achieved?

**Comment by NilsEngelbach** [comment]
I am a bit lost here but really want to try to contribute this feature. I think it provides a lot of benefits and it is not only about the `TransactionScope` in particular, it would also be enough to support `EntityFramework Transactions`:

```c#
public class ExampleService
{
    private readonly ExampleDbContext _dbContext;
    private readonly ISchedulerFactory _schedulerFactory;

    public ExampleService(ISchedulerFactory schedulerFactory, ExampleDbContext dbContext)
    {
        _dbContext = dbContext;
        _schedulerFactory = schedulerFactory;
    }

    public async Task WithEFTransaction()
    {
        using (var dbContextTransaction = _dbContext.Database.BeginTransaction())
        {
            // Make changes to entities
            var entity = _dbContext.ExampleEntities.Add(new ExampleEntity() { Name = new Random().Next(1, 100).ToString() });
            await _dbContext.SaveChangesAsync();

            // Add job for entity
            var scheduler = await _schedulerFactory.GetScheduler();
            
            var job = JobBuilder.Create<ExampleJob>()
                .WithIdentity("exampleJob")
                .UsingJobData("entity-name", entity.Entity.Name)
                .Build();

            var trigger = TriggerBuilder.Create()
                .WithIdentity("exampleTrigger")
                .StartNow()
                .Build();

            await scheduler.ScheduleJob(job, trigger);

            dbContextTransaction.Commit();
        }
    }
}
```

Could you give me a clue how to get the `DbContextJobStore` (dependency injection of a scoped service in the job store) to work?

**Comment by lahma** [comment]
I tried to improve the configuration story a bit with https://github.com/quartznet/quartznet/pull/2063 so if you try to use the example code with latest release from MyGet feed (guidance in readme):

https://github.com/quartznet/quartznet/blob/133c5a34cb39a38c1060ce98c96794bd75344917/src/Quartz.Examples.AspNetCore/Startup.cs#L196-L199

That might guide you further, you store should now support DI via constructor injection.

**Comment by NilsEngelbach** [comment]
Hi @lahma,

With your latest changes I was able to write a simple Entity Framework `DbContextJobStore`:

```c#
builder.Services.AddDbContext<ExampleDbContext>();

builder.Services.AddScoped<DbContextJobStore<ExampleDbContext>>();

builder.Services.AddQuartz(q =>
{
    q.UseMicrosoftDependencyInjectionJobFactory();

    q.UsePersistentStore<DbContextJobStore<ExampleDbContext>>(c =>
    {
        c.UseProperties = true;
        c.UseJsonSerializer();
        c.UsePostgres(b => {
            b.UseDriverDelegate<PostgreSQLDelegate>();
            b.ConnectionString = ExampleDbContext.ConnectionString;
            b.TablePrefix = "quartz.qrtz_";
        });
    });
});
```

```c#
public class DbContextJobStore<C> : JobStoreCMT where C : DbContext
{
    private readonly IServiceProvider _serviceProvider;
    // private readonly C _dbContext;
    private readonly ILogger<DbContextJobStore<C>> _logger;

    public DbContextJobStore(
        IServiceProvider serviceProvider,
        // C dbContext,
        ILogger<DbContextJobStore<C>> logger)
    {
        _serviceProvider = serviceProvider;
        // _dbContext = dbContext;
        _logger = logger;
    }

    protected override async ValueTask<ConnectionAndTransactionHolder> GetNonManagedTXConnection()
    {
        var scope = _serviceProvider.CreateScope();
        var _dbContext = scope.ServiceProvider.GetRequiredService<C>();
        var dbConnection = _dbContext.Database.GetDbConnection();
        if (dbConnection.State != System.Data.ConnectionState.Open)
        {
            await dbConnection.OpenAsync();
        }
        var transaction = _dbContext.Database.CurrentTransaction?.GetDbTransaction();
        return new ConnectionAndTransactionHolder(dbConnection, transaction);
    }

    protected override void CloseConnection(ConnectionAndTransactionHolder connectionAndTransactionHolder)
    {
        connectionAndTransactionHolder.Connection.Close();
    }
}
```

My current problem is that I want to inject the `DbContext` directly without creating a scope from the `ServiceProvider` first, but the DbContext in Entity Framwork has the Lifetime `Scoped` and therefore can not be injected in the `Singleton` `IJobStore`.

Would it be possible to change the Lifetime of the IJobStore to Scoped as well, or make it configurable? Do you see any problem with this?

https://github.com/quartznet/quartznet/blob/bd72782dbd27e4d5aa3eaffd4bab70bdbb6d63f3/src/Quartz/Configuration/ServiceCollectionQuartzConfigurator.cs#L87

Thanks already for the work you already put into this!

**Comment by lahma** [comment]
I'm afraid that changing job store to non-singleton is a no-go currently. Job store also has cluster manager thread etc so that would just basically blow up if there would be a different instance every time.

Are there any alternate designs for this. Like if `ConnectionAndTransactionHolder` would contain a custom field that you could use to transfer some needed state. Or is your current solution already working, you just aren't totally happy with the design?

**Comment by NunoGamaVieira** [comment]
Hi @NilsEngelbach and @lahma,

I am stuck with the same problem. Did you find a way to get the scoped transaction on the jobstore? 
I can't find any more info on this abp-quartz issue besides it being the same they report on abp-hangfire here https://github.com/aspnetboilerplate/aspnetboilerplate/issues/3375.

thanks in advance

**Comment by dazinator** [comment]
> My current problem is that I want to inject the DbContext directly without creating a scope from the ServiceProvider first, but the DbContext in Entity Framwork has the Lifetime Scoped and therefore can not be injected in the Singleton IJobStore.

Why not inject IDbContextFactory instead. You can register this in addition to the normal ef registration. IDbContextFactory will let you create a new instance of a DbContext without having to create a new DI scope.

However I am guessing you are already using a scoped instance of a DbContext and by the time the singletone IJobStore is used, you want it to be resolving your current in scope instance so that it will share a connection? That's a tricky one

How about an Async Local?
1. Surround your usage of the quartz scheduler code with something that sets an Async Local property of some singleton service, with the current DbContext instance.
2. inject that singleton service into your JobStore implementation and grab the DbContext instance from there.

**Comment by ClassTerr** [comment]
That's what worked for me prior upgrading to .NET 10:
```csharp
var txOptions = new TransactionOptions { IsolationLevel = IsolationLevel.ReadCommitted };

using var scope = new TransactionScope(
    TransactionScopeOption.Required,
    txOptions,
    TransactionScopeAsyncFlowOption.Enabled
);

await next(context); // This is a middleware

scope.Complete();
```

After upgrading to .NET 10, I've got a new problem:

> System.NotSupportedException
> Implicit distributed transactions have not been enabled. If you're intentionally starting a distributed transaction, set TransactionManager.ImplicitDistributedTransactions to true.

The solution I've found is to override Application Name in SQL connection string to something custom:
```
Data Source=localhost;Initial Catalog=MyDb;Application Name=MyApi
```
EF Core 10.x started to override the Application Name parameter if not set. That's why the connection strings between EF Core and Quartz were different, so the transaction was promoted to a distributed, and I definitely don't want this.

I'm posting this here, because when upgrading to .NET 10 while having some tests, the Quartz will be one of the first to crash because of this, trying to save time for others.

More info:
https://github.com/dotnet/efcore/issues/36911

**Comment by ClassTerr** [comment]
While the workaround in the previous comment solves the issue for SQL Server, I haven’t found an equivalent solution for PostgreSQL:
Quartz.JobPersistenceException: Failure setting up connection. ---> System.InvalidOperationException: A transaction is already in progress; nested/concurrent transactions aren't supported.

The real problem is that Quartz.NET and EF Core cannot easily participate in the same local transaction unless they share the same underlying connection/transaction. For SQL Server, aligning the connection string can avoid accidental transaction promotion, but I don’t see a comparable workaround for PostgreSQL.

This makes atomic “persist EF Core changes + schedule Quartz job” scenarios difficult to implement reliably. Consumers who care about transactional guarantees may end up implementing an Outbox pattern and then using yet another background job whose purpose is to schedule the actual Quartz background job — which feels a bit ironic.

I believe this issue should be prioritized.

**Comment by lahma** [comment]
> I believe this issue should be prioritized.

You can always prioritize creating a PR suggesting a working fix.
