### ISSUE TITLE
GetScheduler Exception: No writable property 'driverDelegateType' found

### ISSUE THREAD

**Issue by Roiskia** [quartznet/quartznet#2118]
**Describe the bug**

Im trying to get started with Quartz.net for evaluation as described in the [Job Stores Documentation](https://www.quartz-scheduler.net/documentation/quartz-3.x/tutorial/job-stores.html#configuring-quartz-to-use-jobstoretx), but im getting an Exception (see Details below) when i create the scheduler.

Am i missing something?

**Version used**

3.7.0.0

**To Reproduce**

```csharp
public static ISchedulerFactory Factory { get; private set; }

public static IScheduler Scheduler { get; private set; }

protected void Application_Start(object sender, EventArgs e)
{

    var properties = new NameValueCollection
    {
        { "quartz.scheduler.instanceName", "Scheduler" },
        { "quartz.scheduler.instanceId", "1" },
        { "quartz.jobStore.type", "Quartz.Impl.AdoJobStore.JobStoreTX, Quartz" },
        { "quartz.jobStore.driverDelegateType ", "Quartz.Impl.AdoJobStore.OracleDelegate, Quartz" },
        { "quartz.jobStore.useProperties", "true" },
        { "quartz.jobStore.dataSource", "localhost_ora" },
        { "quartz.jobStore.tablePrefix", "QRTZ_" },
        { "quartz.dataSource.localhost_ora.connectionString", @"Server=localhost;Database=system;Uid=system;Pwd=oracle" },
        { "quartz.dataSource.localhost_ora.provider", "OracleODPManaged" },
        { "quartz.serializer.type", "json" },
    };
    
    Factory = new StdSchedulerFactory(properties);

    Scheduler = Factory.GetScheduler().Result; //throws
}
```
Exception Details:
```
System.AggregateException
  HResult=0x80131500
  Message=One or more errors occurred.
  Source=mscorlib
  StackTrace:
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Quartz.Net.Global.Application_Start(Object sender, EventArgs e) in .\Quartz.Net\Quartz.Net\Global.asax.cs:line 34

  This exception was originally thrown at this call stack:
    [External Code]

Inner Exception 1:
SchedulerException: JobStore type 'Quartz.Impl.AdoJobStore.JobStoreTX' props could not be configured.

Inner Exception 2:
SchedulerConfigException: Could not parse property 'driverDelegateType ' into correct data type: No writable property 'driverDelegateType ' found

Inner Exception 3:
MemberAccessException: No writable property 'driverDelegateType ' found
```

**Comment by jafin** [comment]
@Roiskia 
there is a space at the end of `"quartz.jobStore.driverDelegateType "` perhaps try removing the space?

**Comment by lahma** [comment]
You might also want to consider using `SchedulerBuilder` API to remove the need for magic property strings.
