### ISSUE TITLE
Cron expression does not support offsets

### ISSUE THREAD

**Issue by gguillen** [quartznet/quartznet#228]
I am trying to run a job every 2 minutes, on odd minutes using the following cron expression: 0 1-59/2 * 1/1 * ?

Upon reading the configuration file, an exception is thrown:

The 'http://quartznet.sourceforge.net/JobSchedulingData:cron-expression' element is invalid - The value '0 1-59/2 * 1/1 * ?' is invalid according to its datatype 'http://quartznet.sourceforge.net/JobSchedulingData:cron-expressionType' - The Pattern constraint failed.

Quartz.Xml.ValidationException: The 'http://quartznet.sourceforge.net/JobSchedulingData:cron-expression' element is invalid - The value '0 1-59/2 * 1/1 * ?' is invalid according to its datatype 'http://quartznet.sourceforge.net/JobSchedulingData:cron-expressionType' - The Pattern constraint failed.

   at Quartz.Xml.XMLSchedulingDataProcessor.MaybeThrowValidationException()
   at Quartz.Xml.XMLSchedulingDataProcessor.ProcessInternal(String xml)
   at Quartz.Xml.XMLSchedulingDataProcessor.ProcessFile(String fileName, String systemId)
   at Quartz.Xml.XMLSchedulingDataProcessor.ProcessFileAndScheduleJobs(String fileName, String systemId, IScheduler sched)
   at Quartz.Plugin.Xml.XMLSchedulingDataProcessorPlugin.ProcessFile(JobFile jobFile)

**Comment by gguillen** [comment]
Hmm, well, after further experimenting, it seems the following does what I need: 0 1/2 * 1/1 * ?

**Comment by lahma** [comment]
Great that you got that sorted!
