### ISSUE TITLE
"The Scheduler has been Shutdown" from WebApplicationFactory startup

### ISSUE THREAD

**Issue by MrPerun** [quartznet/quartznet#2491]
**Describe the bug**

"The Scheduler has been Shutdown" is sometimes thrown from unit test WebApplicationFactory startup.

I have integration tests with NUnit. My application has Quartz with Scheduler, with MS SQL and clustering. My tests randomly fails with exception:

```
Quartz.SchedulerException : The Scheduler has been Shutdown.
   at Quartz.Core.QuartzScheduler.ValidateState()
   at Quartz.Core.QuartzScheduler.GetJobDetail(JobKey jobKey, CancellationToken cancellationToken)
   at Quartz.Impl.StdScheduler.GetJobDetail(JobKey jobKey, CancellationToken cancellationToken)
   at Quartz.Xml.XMLSchedulingDataProcessor.ScheduleJobs(IScheduler sched, CancellationToken cancellationToken)
   at Quartz.ServiceCollectionSchedulerFactory.InitializeScheduler(IScheduler scheduler, CancellationToken cancellationToken)
   at Quartz.ServiceCollectionSchedulerFactory.GetScheduler(CancellationToken cancellationToken)
   at Quartz.QuartzHostedService.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>b__15_1(IHostedService service, CancellationToken token)
   at Microsoft.Extensions.Hosting.Internal.Host.ForeachService[T](IEnumerable`1 services, CancellationToken token, Boolean concurrent, Boolean abortOnFirstException, List`1 exceptions, Func`3 operation)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at QuartzDemoWebApi.Program.Main(String[] args) in C:\w\POS\QuartzDemo\QuartzDemoWebApi\Program.cs:line 89
   at InvokeStub_Program.Main(Object, Span`1)
   at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Testing.DeferredHostBuilder.DeferredHost.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Start(IHost host)
   at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.CreateHost(IHostBuilder builder)
   at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.ConfigureHostBuilder(IHostBuilder hostBuilder)
   at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.EnsureServer()
   at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.CreateDefaultClient(DelegatingHandler[] handlers)
   at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.CreateDefaultClient(Uri baseAddress, DelegatingHandler[] handlers)
   at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.CreateClient(WebApplicationFactoryClientOptions options)
   at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.CreateClient()
   at QuartzDemoTests.WebTests.Test() in C:\w\POS\QuartzDemo\QuartzDemoTests\WebTests.cs:line 47
   at QuartzDemoTests.WebTests.Test2() in C:\w\POS\QuartzDemo\QuartzDemoTests\WebTests.cs:line 36
   at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.GetResult()
   at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
   at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.<>c__DisplayClass1_0.<Execute>b__0()
   at NUnit.Framework.Internal.Commands.DelegatingTestCommand.RunTestMethodInThreadAbortSafeZone(TestExecutionContext context, Action action)
```

The exception is throw from Web Host startup.

I run the tests strictly sequentially - "dotnet test ... NUnit.NumberOfTestWorkers=1"

I double checked that for each test instance, there is always fresh instance of the WebApplicationFactory and the ISchedulerFactory.

Problem doesn't occur if I use different SchedulerName for each test. It could be solution for tests. But I'm afraid of production behavior - not sure if the problem affects only the tests.

I also didn't note the problem when using in memory store instead. But it may be only a coincidence.

I thought about calling Scheduler.Start() manually somewhere, but it looks not to be possible, as the exception is thrown during the startup, in the "scheduler entry point" ServiceCollectionSchedulerFactory.GetScheduler(). So not possible to get the scheduler instance on time.

**Version used**

Quartz 3.11.0, same problem with 3.8.1

**To Reproduce**

See test application: https://github.com/MrPerun/QuartzDemo

- Set ConnectionString in appsettings.Development.json
- deploy Quartz DB by `dotnet ef database update`
- Run the tests either from IDE (with NUnit.NumberOfTestWorkers=1), or by prepared infinte loop script `QuartzDemoTests\RunTests.ps1`

Sometimes it fails after a few runs, sometimes it runs up to 15 minutes without problem.

**Comment by lahma** [comment]
With #2498 shutdown logic should be now more robust and ensure cleanup after old host.
