### ISSUE TITLE
Culture-specific sql generation in StdAdoConstants

### ISSUE THREAD

**Issue by d-kartish** [quartznet/quartznet#2565]
**Describe the bug**

StdAdoConstants uses string interpolation to form sql. Some cultures have a non-standard representation of negative numbers. For example lt, sl, et cultures.

Because of this, all sql with MisfireInstruction.IgnoreMisfirePolicy are invalid.

```
MySqlConnector.MySqlException (0x80004005): Unknown column '−1' in 'where clause'
   at MySqlConnector.Core.ServerSession.ReceiveReplyAsync(IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ServerSession.cs:line 886
   at MySqlConnector.Core.ResultSet.ReadResultSetHeaderAsync(IOBehavior ioBehavior) in /_/src/MySqlConnector/Core/ResultSet.cs:line 183
   at MySqlConnector.MySqlDataReader.ActivateResultSet(CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 133
   at MySqlConnector.MySqlDataReader.InitAsync(CommandListPosition commandListPosition, ICommandPayloadCreator payloadCreator, IDictionary`2 cachedProcedures, IMySqlCommand command, CommandBehavior behavior, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 504
   at MySqlConnector.Core.CommandExecutor.ExecuteReaderAsync(CommandListPosition commandListPosition, ICommandPayloadCreator payloadCreator, CommandBehavior behavior, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/CommandExecutor.cs:line 78
   at MySqlConnector.MySqlCommand.ExecuteReaderAsync(CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlCommand.cs:line 358
   at MySqlConnector.MySqlCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlCommand.cs:line 350
   at Quartz.Impl.AdoJobStore.StdAdoDelegate.HasMisfiredTriggersInState(ConnectionAndTransactionHolder conn, String state1, DateTimeOffset ts, Int32 count, ICollection`1 resultList, CancellationToken cancellationToken)
   at Quartz.Impl.AdoJobStore.JobStoreSupport.RecoverMisfiredJobs(ConnectionAndTransactionHolder conn, Boolean recovering, CancellationToken cancellationToken)
   at Quartz.Impl.AdoJobStore.JobStoreSupport.DoRecoverMisfires(Guid requestorId, CancellationToken cancellationToken) Server Error Code: 1054;SqlState: 42S22
```

**Version used**

3.13.0

**To Reproduce**

```csharp
[Test]
public void ReproduceNegativeSignIssueForSpecificCulture()
{
    var cultureInfo = new CultureInfo("lt-LT");
    var expectedNegativeNumber = MisfireInstruction.IgnoreMisfirePolicy.ToString(CultureInfo.InvariantCulture);

    Thread.CurrentThread.CurrentCulture = cultureInfo;

    var sql = StdAdoConstants.SqlSelectMisfiredTriggers;
    
    Assert.That(sql, Does.Contain(expectedNegativeNumber));
}
```

**Expected behavior**

sql scripts are culture independent.

**Additional context**

A temporary solution is to make a custom class from the StdAdoDelegate (or MySQLDelegate, etc.) and override the problematic sql.
The correct solution is to use CultureInfo.InvariantCulture when storing formatted data ([MS docs](https://learn.microsoft.com/en-us/dotnet/standard/base-types/best-practices-display-data#persist-formatted-data)). 

`StdAdoConstants.cs`

```csharp
public static readonly string SqlSelectMisfiredTriggers =
        $"SELECT * FROM {TablePrefixSubst}{TableTriggers} WHERE {ColumnSchedulerName} = @schedulerName AND {ColumnMifireInstruction} <> {MisfireInstruction.IgnoreMisfirePolicy.ToString(CultureInfo.InvariantCulture)} AND {ColumnNextFireTime} < @nextFireTime ORDER BY {ColumnNextFireTime} ASC, {ColumnPriority} DESC";

    public static readonly string SqlSelectMisfiredTriggersInGroupInState =
        $"SELECT {ColumnTriggerName} FROM {TablePrefixSubst}{TableTriggers} WHERE {ColumnSchedulerName} = @schedulerName AND {ColumnMifireInstruction} <> {MisfireInstruction.IgnoreMisfirePolicy.ToString(CultureInfo.InvariantCulture)} AND {ColumnNextFireTime} < @nextFireTime AND {ColumnTriggerGroup} = @triggerGroup AND {ColumnTriggerState} = @state ORDER BY {ColumnNextFireTime} ASC, {ColumnPriority} DESC";

    public static readonly string SqlSelectMisfiredTriggersInState =
        $"SELECT {ColumnTriggerName}, {ColumnTriggerGroup} FROM {TablePrefixSubst}{TableTriggers} WHERE {ColumnSchedulerName} = @schedulerName AND {ColumnMifireInstruction} <> {MisfireInstruction.IgnoreMisfirePolicy.ToString(CultureInfo.InvariantCulture)} AND {ColumnNextFireTime} < @nextFireTime AND {ColumnTriggerState} = @state ORDER BY {ColumnNextFireTime} ASC, {ColumnPriority} DESC";

    public static readonly string SqlCountMisfiredTriggersInStates =
        $"SELECT COUNT({ColumnTriggerName}) FROM {TablePrefixSubst}{TableTriggers} WHERE {ColumnSchedulerName} = @schedulerName AND {ColumnMifireInstruction} <> {MisfireInstruction.IgnoreMisfirePolicy.ToString(CultureInfo.InvariantCulture)} AND {ColumnNextFireTime} < @nextFireTime AND {ColumnTriggerState} = @state1";

    public static readonly string SqlSelectHasMisfiredTriggersInState =
        $"SELECT {ColumnTriggerName}, {ColumnTriggerGroup} FROM {TablePrefixSubst}{TableTriggers} WHERE {ColumnSchedulerName} = @schedulerName AND {ColumnMifireInstruction} <> {MisfireInstruction.IgnoreMisfirePolicy.ToString(CultureInfo.InvariantCulture)} AND {ColumnNextFireTime} < @nextFireTime AND {ColumnTriggerState} = @state1 ORDER BY {ColumnNextFireTime} ASC, {ColumnPriority} DESC";
```

**Comment by lahma** [comment]
That was quite the issue, thanks for reporting.
