### ISSUE TITLE
Source file '..\AssemblyInfo.cs' could not be found

### ISSUE THREAD

**Issue by mobedi** [quartznet/quartznet#327]
Upon building the latest commit's solution (either by opening `Quartz.2010.sln` or `Quartz.Server.2010.sln`)  I get the error

> Source file '..\AssemblyInfo.cs' could not be found

Any ideas?

**Comment by lahma** [comment]
Please run Build.cmd first to generate AssemblyInfo.cs

**Comment by mobedi** [comment]
Hi! I get the following exception after running the build.cmd file:
```
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Windows\system32>cd C:\Users\pedram.mobedi\Desktop\quartznet-master\quartznet
-master

C:\Users\pedram.mobedi\Desktop\quartznet-master\quartznet-master>build.cmd

C:\Users\pedram.mobedi\Desktop\quartznet-master\quartznet-master>tools\nant\bin\
nant clean build  1>buildlog.txt
log4net:ERROR XmlConfiguratorAttribute: Exception getting ConfigurationFileLocat
ion. Must be able to resolve ConfigurationFileLocation when ConfigFile and Confi
gFileExtension properties are not set.
System.Security.SecurityException: Request for the permission of type 'System.Se
curity.Permissions.FileIOPermission, mscorlib, Version=4.0.0.0, Culture=neutral,
 PublicKeyToken=b77a5c561934e089' failed.
   at System.Security.CodeAccessSecurityEngine.Check(Object demand, StackCrawlMa
rk& stackMark, Boolean isPermSet)
   at System.Security.CodeAccessPermission.Demand()
   at System.AppDomainSetup.VerifyDir(String dir, Boolean normalize)
   at log4net.Config.XmlConfiguratorAttribute.ConfigureFromFile(Assembly sourceA
ssembly, ILoggerRepository targetRepository)
The action that failed was:
Demand
The type of the first permission that failed was:
System.Security.Permissions.FileIOPermission
The Zone of the assembly that failed was:
Internet

Unhandled Exception: System.Security.SecurityException: Request for Configuratio
nPermission failed while attempting to access configuration section 'nant'. To a
llow all callers to access the data for this section, set section attribute 'req
uirePermission' equal 'false' in the configuration file where this section is de
clared. ---> System.Security.SecurityException: Request for the permission of ty
pe 'System.Configuration.ConfigurationPermission, System.Configuration, Version=
4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' failed.
   at System.Security.CodeAccessSecurityEngine.Check(Object demand, StackCrawlMa
rk& stackMark, Boolean isPermSet)
   at System.Security.CodeAccessPermission.Demand()
   at System.Configuration.BaseConfigurationRecord.CheckPermissionAllowed(String
 configKey, Boolean requirePermission, Boolean isTrustedWithoutAptca)
   --- End of inner exception stack trace ---
   at System.Configuration.BaseConfigurationRecord.CheckPermissionAllowed(String
 configKey, Boolean requirePermission, Boolean isTrustedWithoutAptca)
   at System.Configuration.BaseConfigurationRecord.GetSectionRecursive(String co
nfigKey, Boolean getLkg, Boolean checkPermission, Boolean getRuntimeObject, Bool
ean requestIsHere, Object& result, Object& resultRuntimeObject)
   at System.Configuration.BaseConfigurationRecord.GetSection(String configKey)
   at System.Configuration.ConfigurationManager.GetSection(String sectionName)
   at NAnt.Console.ConsoleStub.Framework.GetRuntimeFramework()
   at NAnt.Console.ConsoleStub.Main(String[] args)

C:\Users\pedram.mobedi\Desktop\quartznet-master\quartznet-master>
```

**Comment by lahma** [comment]
If you have downloaded the source as a zip file you should unblock the zip file before extracting the contents.
