### ISSUE TITLE
Most examples are broken in quartznet-3 branche

### ISSUE THREAD

**Issue by GieltjE** [quartznet/quartznet#358]
Example[1-7][9-11]:
2016-04-25 10:25:33,160 [19] ERROR Quartz.Core.QuartzSchedulerThread - Runtime error occurred in main trigger firing loop.
System.NotSupportedException: This ThreadPool should not be used for running async jobs
   at Quartz.Simpl.SimpleThreadPool.RunInThread(Func`1 runnable) in X:\quartznet\src\Quartz\Simpl\SimpleThreadPool.cs:line 305
   at Quartz.Core.QuartzSchedulerThread.<Run>d__29.MoveNext() in X:\quartznet\src\Quartz\Core\QuartzSchedulerThread.cs:line 428

**Comment by lahma** [comment]
Thanks for reporting, should be fixed now.
