### ISSUE TITLE
The type initializer for 'Quartz.Impl.StdSchedulerFactory' threw an exception.

### ISSUE THREAD

**Issue by agonzalezm** [quartznet/quartznet#383]
I have updated to serilog 2.0 and now get an exception in Quartz, any workaround or fix for it?

Method 'ForContext' in type 'Common.Logging.Serilog.SerilogInstanceWrapper' from assembly 'Common.Logging.Serilog, Version=3.1.6.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
   at Common.Logging.Serilog.SerilogFactoryAdapter.GetLogger(Type type)
   at Common.Logging.LogManager.GetLogger(Type type) in c:_oss\common-logging\src\Common.Logging.Portable\Logging\LogManager.cs:line 422
   at Quartz.Impl.StdSchedulerFactory..cctor() in c:\Program Files (x86)\Jenkins\workspace\Quartz.NET\src\Quartz\Impl\StdSchedulerFactory.cs:line 135

**Comment by lahma** [comment]
Closing as more question for Common.Logging and serilog integration. Quartz.NET v3 will use LibLog which will hopefully make things easier.
