### ISSUE TITLE
Quartz.Core.QuartzSchedulerThread.Run Error quartzSchedulerThreadLoop: RuntimeException Not Cloneable

### ISSUE THREAD

**Issue by cubikca** [quartznet/quartznet#408]
```
2016-09-20 14:34:08.3252 Quartz.Core.QuartzSchedulerThread.Run Error quartzSchedulerThreadLoop: RuntimeException Not Cloneable. System.Exception: Not Cloneable.
   at Quartz.CronExpression.Clone() in c:\Program Files (x86)\Jenkins\workspace\Quartz.NET\src\Quartz\CronExpression.cs:line 2108
   at Quartz.Impl.Triggers.CronTriggerImpl.Clone() in c:\Program Files (x86)\Jenkins\workspace\Quartz.NET\src\Quartz\Impl\Triggers\CronTriggerImpl.cs:line 396
   at Quartz.Simpl.RAMJobStore.AcquireNextTriggers(DateTimeOffset noLaterThan, Int32 maxCount, TimeSpan timeWindow) in c:\Program Files (x86)\Jenkins\workspace\Quartz.NET\src\Quartz\Simpl\RAMJobStore.cs:line 1552
   at Quartz.Core.QuartzSchedulerThread.Run() in c:\Program Files (x86)\Jenkins\workspace\Quartz.NET\src\Quartz\Core\QuartzSchedulerThread.cs:line 253
```

This is on version 2.4.1, running on Windows Server 2012. The job in question has the following cron schedule defined:

0/10 \* \* \* \* ?

This is a polling job that prints reports generated by our webapp. It is tagged with the DisallowConcurrentExecutionAttribute.

**Comment by lahma** [comment]
This means that the expression is no longer valid. Have you changed the expression by directly updating the database?

**Comment by cubikca** [comment]
The cron expression is pulled at startup from the app.config at runtime (see my comment in #409). I don't see how we could have changed it.

**Comment by lahma** [comment]
Is there more lines to this exception? There should be an inner exception with more details about what went wrong with expression parsing.

**Comment by cubikca** [comment]
No, this is all that was logged :(

Is there any way of catching this error? Currently we're monitoring the logs for quartzSchedulerThreadLoop RuntimeExceptions, and restarting the Windows Service if it happens. We really can't afford to have this job crash.

**Comment by lahma** [comment]
I'm closing this as hard to reproduce, if we can get more details and a good repro we can try to fix this.
