### ISSUE TITLE
Quartz.Core.ErrorLogger.SchedulerError

### ISSUE THREAD

**Issue by cubikca** [quartznet/quartznet#409]
```
2016-09-20 17:04:29.7644 Quartz.Core.ErrorLogger.SchedulerError Error Please report this error to the Quartz developers. Quartz.SchedulerException: Trigger threw an unhandled exception. ---> System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.Text.StringBuilder..ctor(String value, Int32 startIndex, Int32 length, Int32 capacity)
   at NLog.Layouts.SimpleLayout.GetFormattedMessage(LogEventInfo logEvent)
   at NLog.Targets.FileTarget.GetFormattedMessage(LogEventInfo logEvent)
   at NLog.Targets.FileTarget.GetBytesToWrite(LogEventInfo logEvent)
   at NLog.Targets.FileTarget.Write(LogEventInfo logEvent)
   at NLog.Targets.Target.Write(AsyncLogEventInfo logEvent)
   at NLog.Targets.Target.WriteAsyncLogEvent(AsyncLogEventInfo logEvent)
   at NLog.LoggerImpl.WriteToTargetWithFilterChain(TargetWithFilterChain targetListHead, LogEventInfo logEvent, AsyncContinuation onException)
   at NLog.LoggerImpl.Write(Type loggerType, TargetWithFilterChain targets, LogEventInfo logEvent, LogFactory factory)
   at NLog.Logger.WriteToTargets(Type wrapperType, LogEventInfo logEvent)
   at NLog.Logger.Log(Type wrapperType, LogEventInfo logEvent)
   at Common.Logging.NLog.NLogLogger.WriteInternal(LogLevel logLevel, Object message, Exception exception) in c:\_oss\common-logging\src\Common.Logging.NLog10\Logging\NLog\NLogLogger.cs:line 951
   at Common.Logging.NLog.NLogLogger.Debug(Object message) in c:\_oss\common-logging\src\Common.Logging.NLog10\Logging\NLog\NLogLogger.cs:line 272
   at Quartz.Core.JobRunShell.Run() in c:\Program Files (x86)\Jenkins\workspace\Quartz.NET\src\Quartz\Core\JobRunShell.cs:line 221
   --- End of inner exception stack trace --- [See nested exception: System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.Text.StringBuilder..ctor(String value, Int32 startIndex, Int32 length, Int32 capacity)
   at NLog.Layouts.SimpleLayout.GetFormattedMessage(LogEventInfo logEvent)
   at NLog.Targets.FileTarget.GetFormattedMessage(LogEventInfo logEvent)
   at NLog.Targets.FileTarget.GetBytesToWrite(LogEventInfo logEvent)
   at NLog.Targets.FileTarget.Write(LogEventInfo logEvent)
   at NLog.Targets.Target.Write(AsyncLogEventInfo logEvent)
   at NLog.Targets.Target.WriteAsyncLogEvent(AsyncLogEventInfo logEvent)
   at NLog.LoggerImpl.WriteToTargetWithFilterChain(TargetWithFilterChain targetListHead, LogEventInfo logEvent, AsyncContinuation onException)
   at NLog.LoggerImpl.Write(Type loggerType, TargetWithFilterChain targets, LogEventInfo logEvent, LogFactory factory)
   at NLog.Logger.WriteToTargets(Type wrapperType, LogEventInfo logEvent)
   at NLog.Logger.Log(Type wrapperType, LogEventInfo logEvent)
   at Common.Logging.NLog.NLogLogger.WriteInternal(LogLevel logLevel, Object message, Exception exception) in c:\_oss\common-logging\src\Common.Logging.NLog10\Logging\NLog\NLogLogger.cs:line 951
   at Common.Logging.NLog.NLogLogger.Debug(Object message) in c:\_oss\common-logging\src\Common.Logging.NLog10\Logging\NLog\NLogLogger.cs:line 272
   at Quartz.Core.JobRunShell.Run() in c:\Program Files (x86)\Jenkins\workspace\Quartz.NET\src\Quartz\Core\JobRunShell.cs:line 221]
```
We can find no application code that would have ran the system out of memory. In fact, only one job (the job referred to in #408) was scheduled to run at the the time. The Windows Service was restarted after reporting the issue. Again, we can find no issues with the application code in this job.

**Comment by lahma** [comment]
Have you created custom trigger or something similar? This exceptions is a signal about trigger misbehaving and the built-in ones pretty much battle-tested...

**Comment by cubikca** [comment]
We use the following to initialize new jobs:

```c#
        private static void AddCronJob<T>() where T : IJob
        {
            var jobName = typeof (T).Name;
            try
            {
                var triggerName = jobName + "Job";
                const string groupName = "SystemTx";
                var cron = ConfigurationManager.AppSettings[jobName + "Schedule"];
                if (cron != "OFF" && cron != "off")
                {
                    IJob job = Activator.CreateInstance<T>();
                    var detail = new JobDetailImpl(triggerName, groupName, job.GetType());
                    var trigger = new CronTriggerImpl(
                            triggerName,
                            groupName,
                            cron)
                    { TimeZone = TimeZoneInfo.Local };
                    _scheduler.ScheduleJob(detail, trigger);
                    var nextExecution = trigger.GetNextFireTimeUtc();
                    if (nextExecution != null)
                        Log.Info(groupName + "+" + jobName + ": " + nextExecution.Value.ToString("u"));
                    else
                        Log.Warn("Invalid schedule for " + jobName);
                }
                else
                {
                    Log.Warn("Job status 'OFF' for " + jobName);
                }
            }
            catch (Exception ex)
            {
                Log.Error("Unable to Initialize Job " + jobName, ex);
            }
        }
```

**Comment by lahma** [comment]
Somehow it would seem that NLog is the culprit, the exception is thrown when Quartz tries to write Debug level log message. Is there anything special with NLog configuration, just writing to file?

The debug level can produce a lot of noise so I wonder if NLog could choke when it cannot write all data to disk(?) as fast as it should.

**Comment by lahma** [comment]
There's some discussion on NLog's issue tracker too: https://github.com/NLog/NLog/issues/513

**Comment by cubikca** [comment]
OK, we'll look into the NLog side, thanks.
