### ISSUE TITLE
Can't reschedule clustered jobs 

### ISSUE THREAD

**Issue by shadowfoxish** [quartznet/quartznet#434]
https://github.com/shadowfoxish/Temp-QuartzIssue 

I created the above repo with a demo solution to exercise an issue I'm having with using Quartz in a clustered service environment. The clustering is being done with MSSQL 2008R2, and the most recent DB setup script provided by the quartz team.

Basically, what I'm doing is creating a service which watches a text file for changes. If the file changes, the service would (presumably) reach out to its configuration store, cache some settings in memory (which can include job scheduling data) and reconfigure the jobs with the new cached data. I omitted some of that since it isn't necessary to demonstrate the issue. 

Anyway, when running this as a single process there's no issue. When running it with more than one process, it blows up with this exception.
```
Quartz.JobPersistenceException: Couldn't store job: Unable to store Job: 'DEFAULT.DummyJob', because one already exists with this identification. ---> Quartz.ObjectAlreadyExistsException: Unable to store Job: 'DEFAULT.DummyJob', because one already exists with this identification.
   at Quartz.Impl.AdoJobStore.JobStoreSupport.StoreJob(ConnectionAndTransactionHolder conn, IJobDetail newJob, Boolean replaceExisting) in c:\Program Files (x86)\Jenkins\workspace\Quartz.NET\src\Quartz\Impl\AdoJobStore\JobStoreSupport.cs:line 913
   --- End of inner exception stack trace ---
   at Quartz.Impl.AdoJobStore.JobStoreSupport.StoreJob(ConnectionAndTransactionHolder conn, IJobDetail newJob, Boolean replaceExisting) in c:\Program Files (x86)\Jenkins\workspace\Quartz.NET\src\Quartz\Impl\AdoJobStore\JobStoreSupport.cs:line 928
   at Quartz.Impl.AdoJobStore.JobStoreSupport.<>c__DisplayClass4.<StoreJobAndTrigger>b__3(ConnectionAndTransactionHolder conn) in c:\Program Files (x86)\Jenkins\workspace\Quartz.NET\src\Quartz\Impl\AdoJobStore\JobStoreSupport.cs:line 855
   at Quartz.Impl.AdoJobStore.JobStoreSupport.ExecuteInNonManagedTXLock[T](String lockName, Func`2 txCallback, Func`3 txValidator) in c:\Program Files (x86)\Jenkins\workspace\Quartz.NET\src\Quartz\Impl\AdoJobStore\JobStoreSupport.cs:line 3562
   at Quartz.Impl.AdoJobStore.JobStoreSupport.ExecuteInNonManagedTXLock[T](String lockName, Func`2 txCallback) in c:\Program Files (x86)\Jenkins\workspace\Quartz.NET\src\Quartz\Impl\AdoJobStore\JobStoreSupport.cs:line 3498
   at Quartz.Impl.AdoJobStore.JobStoreTX.ExecuteInLock[T](String lockName, Func`2 txCallback) in c:\Program Files (x86)\Jenkins\workspace\Quartz.NET\src\Quartz\Impl\AdoJobStore\JobStoreTX.cs:line 76
   at Quartz.Impl.AdoJobStore.JobStoreSupport.StoreJobAndTrigger(IJobDetail newJob, IOperableTrigger newTrigger) in c:\Program Files (x86)\Jenkins\workspace\Quartz.NET\src\Quartz\Impl\AdoJobStore\JobStoreSupport.cs:line 853
   at Quartz.Core.QuartzScheduler.ScheduleJob(IJobDetail jobDetail, ITrigger trigger) in c:\Program Files (x86)\Jenkins\workspace\Quartz.NET\src\Quartz\Core\QuartzScheduler.cs:line 718
   at Quartz.Impl.StdScheduler.ScheduleJob(IJobDetail jobDetail, ITrigger trigger) in c:\Program Files (x86)\Jenkins\workspace\Quartz.NET\src\Quartz\Impl\StdScheduler.cs:line 262
   at QuartzJobRunner.MyService.ConfigureJob() in c:\users\user\documents\visual studio 2015\Projects\QuartzJobRunner\QuartzJobRunner\Program.cs:line 111
   at QuartzJobRunner.MyService.SettingsCache_SettingsCacheFileChanged(Object sender, EventArgs e) in c:\users\user\documents\visual studio 2015\Projects\QuartzJobRunner\QuartzJobRunner\Program.cs:line 117
   at QuartzJobRunner.SettingsCache.NotifyEvent(Object sender) in c:\users\user\documents\visual studio 2015\Projects\QuartzJobRunner\QuartzJobRunner\Program.cs:line 152
   at QuartzJobRunner.SettingsCache.<>c.<.cctor>b__6_0(Object s, FileSystemEventArgs e) in c:\users\user\documents\visual studio 2015\Projects\QuartzJobRunner\QuartzJobRunner\Program.cs:line 159
   at System.IO.FileSystemWatcher.OnChanged(FileSystemEventArgs e)
   at System.IO.FileSystemWatcher.NotifyFileSystemEventArgs(Int32 action, String name)
   at System.IO.FileSystemWatcher.CompletionStatusChanged(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* overlappedPointer)
   at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pOVERLAP) [See nested exception: Quartz.ObjectAlreadyExistsException: Unable to store Job: 'DEFAULT.DummyJob', because one already exists with this identification.
   at Quartz.Impl.AdoJobStore.JobStoreSupport.StoreJob(ConnectionAndTransactionHolder conn, IJobDetail newJob, Boolean replaceExisting) in c:\Program Files (x86)\Jenkins\workspace\Quartz.NET\src\Quartz\Impl\AdoJobStore\JobStoreSupport.cs:line 913]
```

I have tried a bunch of different ways to reschedule the jobs (using CheckExisting and deleting stuff, caching IJobDetails in memory, not re-saving jobs), but I keep running into this exception or another similar one, depending on how I do it. It all points to an issue with concurrency at the DB JobStore level. Is this a bug or am I doing something nuts? If it isn't a bug, are there any pointers on how I can do this correctly? (Trapping the exception, doing a thread.sleep, and then trying to schedule the job again just feels dirty 😛 )

For posterity, here is the main program code:
```c#
using System;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.Configuration;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using Quartz;
using Quartz.Impl;
using Topshelf;

namespace QuartzJobRunner
{
	class Program
	{
		/// <summary>
		/// To run this sample,
		/// 1) create a folder 'C:\QuartzTest' and place a text file 'CacheFile.txt' in it.
		///     Any time you make a change to that file, the quartz jobs should be re-scheduled.
		/// 2) Setup a quartz DB using the scripts from the Quartz download package
		/// 3) Run two instances of this application. It should come alive correctly and log that the job is working.
		/// 4) Then, edit the cache file and watch both services try to save the same job at the same time. This will 
		/// in most attempts generate an exception in at least one of the two app instances.
		/// </summary>
		static void Main(string[] args)
		{
			Console.WriteLine("Starting App");

			HostFactory.Run(x =>
			{
				x.Service<MyService>(s =>
				{
					s.ConstructUsing(name => new MyService());
					s.WhenStarted(tc => tc.Start());
					s.WhenStopped(tc => tc.Stop());
				});
				x.RunAsLocalSystem();
				x.SetDescription("Quartz Demo");
				x.SetDisplayName("Quartz Demo");
				x.SetServiceName("Quartz Demo");
			});
		}
	}

	class MyService
	{
		IScheduler quartzScheduler;

		public void Start()
		{
			SettingsCache.SettingsCacheFileChanged += SettingsCache_SettingsCacheFileChanged;

			NameValueCollection properties = new NameValueCollection();
			properties["quartz.scheduler.instanceName"] = "AUTO";
			properties["quartz.scheduler.instanceId"] = "AUTO";
			properties["quartz.threadPool.type"] = "Quartz.Simpl.SimpleThreadPool, Quartz";
			properties["quartz.threadPool.threadCount"] = "5";
			properties["quartz.threadPool.threadPriority"] = "Normal";
			properties["quartz.jobStore.misfireThreshold"] = "60000";
			properties["quartz.jobStore.type"] = "Quartz.Impl.AdoJobStore.JobStoreTX, Quartz";
			properties["quartz.jobStore.driverDelegateType"] = "Quartz.Impl.AdoJobStore.SqlServerDelegate, Quartz";
			properties["quartz.jobStore.useProperties"] = "false";
			properties["quartz.jobStore.dataSource"] = "default";
			properties["quartz.jobStore.clusterCheckinInterval"] = "15000";
			//TODO Update this prefix if your table names are prefixed differently
			properties["quartz.jobStore.tablePrefix"] = "QRTZ";
			properties["quartz.jobStore.clustered"] = "true";
			properties["quartz.jobStore.lockHandler.type"] = "Quartz.Impl.AdoJobStore.UpdateLockRowSemaphore, Quartz";
			//TODO Update this connection string to point to your enviro
			properties["quartz.dataSource.default.connectionString"] = @"Server=machinename;Database=Jobs;User ID=userid;Password=classified;Min Pool Size=1;Max Pool Size=15;Connection Timeout=180;Pooling=True;";
			properties["quartz.dataSource.default.provider"] = "SqlServer-20";

			quartzScheduler = new StdSchedulerFactory(properties).GetScheduler();
			
			quartzScheduler.Start();

			ConfigureJob();
		}

		private void ConfigureJob()
		{
			quartzScheduler.Clear();

			IJobDetail job = JobBuilder.Create<DummyJob>()
					.WithIdentity(nameof(DummyJob))
					.StoreDurably(false)
					.Build();

			//Each time the cache is reset, actual app goes out and grabs new configuration from the database, which would then be accessed
			//  here to potentially change the schedule of the job
			TimeSpan interval = new TimeSpan(0, 0, 0, 5); //5s
			Console.WriteLine($"Creating new {nameof(DummyJob)} with interval of {interval}");

			ITrigger trigger = TriggerBuilder.Create()
				.WithIdentity(nameof(DummyJob) + "Trigger", "MyTriggers")
				.WithSimpleSchedule(s => s.WithInterval(interval).RepeatForever())
				.ForJob(job.Key)
				.StartNow()
				.Build();

			quartzScheduler.ScheduleJob(job, trigger);
		}

		private void SettingsCache_SettingsCacheFileChanged(object sender, EventArgs e)
		{
			Console.WriteLine("Reconfiguring job due to cachefile write");
			ConfigureJob();
		}

		public void Stop()
		{
			quartzScheduler.Shutdown();
		}
	}

	class DummyJob : IJob
	{
		public void Execute(IJobExecutionContext context)
		{
			Console.WriteLine($"{DateTime.Now.ToString("HH:mm:ss.fff")} {Thread.CurrentThread.Name} - I'm running now, yay");
		}
	}

	static class SettingsCache
	{
		static FileSystemWatcher ChangeMonitor;

		public static event EventHandler SettingsCacheFileChanged;
		private static long LastChangeNotification;

		private static void NotifyEvent(object sender)
		{
			//Debounce the FS events to once every half-second
			//Antivirus or other FS hooks cause multiple events
			long now = DateTime.Now.Ticks;
			if ((now - SettingsCache.LastChangeNotification) < (TimeSpan.TicksPerMillisecond * 500))
			{
				return;
			}
			SettingsCache.LastChangeNotification = now;

			SettingsCacheFileChanged?.Invoke(sender, new EventArgs());
		}

		static SettingsCache()
		{
			SettingsCache.ChangeMonitor = new FileSystemWatcher("C:\\QuartzTest\\", "CacheFile.txt");
			SettingsCache.ChangeMonitor.NotifyFilter = NotifyFilters.LastWrite;
			SettingsCache.ChangeMonitor.Changed += (s, e) => NotifyEvent(s);
			SettingsCache.ChangeMonitor.EnableRaisingEvents = true;
		}
	}
}
```

Tags: Quartz, Clustered jobs, AdoJobStore, concurrency

**Comment by lahma** [comment]
I think you might want to reconsider some of the implementation, how about:

* store job just once as durable, triggers are the ones that are changing
* have a coordinator that handles scheduling, it can have non-running schduler (no .Start() called) with ZeroSizeThreadPool, this coordinator can handle file change events and make sure schedules are synced to DB and thus reflected to actual work horses (schedulers which are running), now you are just racing against yourself
