### ISSUE TITLE
Cannot use postgresql as jobstore in dotnet core

### ISSUE THREAD

**Issue by gigalink** [quartznet/quartznet#449]
When I configured the JobStore to use postgresql, it throws an exception which says "Could not load type 'Npgsql.NpgsqlCommandBuilder' from assembly 'Npgsql, Version=3.1.2.0, ...". Then I found the cause in https://github.com/npgsql/npgsql/blob/v3.2.0/src/Npgsql/NpgsqlCommandBuilder.cs , the class "NpgsqlCommandBuilder" doesn't exist in dotnet core.

**Comment by lahma** [comment]
A stack trace would be helpful, can you provide one?

**Comment by gigalink** [comment]
Here is the stack trace message. 
[2017/2/15 9:59:21] [Info] Quartz.NET properties loaded from configuration file 'D:\Projects\DotNet\DotNetCore\QuartzDemo\QuartzDemo\bin\Debug\netcoreapp1.0\quartz.config'
Quartz.SchedulerException: Could not Initialize DataSource: myPG ---> System.ArgumentException: Error while reading metadata information for provider 'Npgsql-31'
Parameter name: providerName ---> Quartz.SchedulerConfigException: Could not parse property 'commandBuilderType' into correct data type: Could not load type 'Npgsql.NpgsqlCommandBuilder' from assembly 'Npgsql, Version=3.1.2.0, Culture=neutral, PublicKeyToken=5d8b90d52f46fda7'. ---> System.TypeLoadException: Could not load type 'Npgsql.NpgsqlCommandBuilder' from assembly 'Npgsql, Version=3.1.2.0, Culture=neutral, PublicKeyToken=5d8b90d52f46fda7'.
   at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMarkHandle stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName, ObjectHandleOnStack type, ObjectHandleOnStack keepalive)
   at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName)
   at System.RuntimeType.GetType(String typeName, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMark& stackMark)
   at System.Type.GetType(String typeName, Boolean throwOnError)
   at Quartz.Util.ObjectUtils.ConvertValueIfNecessary(Type requiredType, Object newValue)
   at Quartz.Util.ObjectUtils.SetPropertyValue(Object target, String propertyName, Object value)
   at Quartz.Util.ObjectUtils.SetObjectProperties(Object obj, NameValueCollection props)
   --- End of inner exception stack trace ---
   at Quartz.Util.ObjectUtils.SetObjectProperties(Object obj, NameValueCollection props)
   at Quartz.Impl.AdoJobStore.Common.EmbeddedAssemblyResourceDbMetadataFactory.GetDbMetadata(String providerName)
   --- End of inner exception stack trace ---
   at Quartz.Impl.AdoJobStore.Common.EmbeddedAssemblyResourceDbMetadataFactory.GetDbMetadata(String providerName)
   at Quartz.Impl.AdoJobStore.Common.DbProvider.GetDbMetadata(String providerName)
   at Quartz.Impl.AdoJobStore.Common.DbProvider..ctor(String dbProviderName, String connectionString)
   at Quartz.Impl.StdSchedulerFactory.<Instantiate>d__66.MoveNext()
   --- End of inner exception stack trace ---
   at Quartz.Impl.StdSchedulerFactory.<Instantiate>d__66.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Quartz.Impl.StdSchedulerFactory.<GetScheduler>d__70.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Program.<RunProgram>d__1.MoveNext() in D:\Projects\DotNet\DotNetCore\QuartzDemo\QuartzDemo\Program.cs:line 26 [See nested exception: System.ArgumentException: Error while reading metadata information for provider 'Npgsql-31' Parameter name: providerName ---> Quartz.SchedulerConfigException: Could not parse property 'commandBuilderType' into correct data type: Could not load type'Npgsql.NpgsqlCommandBuilder' from assembly 'Npgsql, Version=3.1.2.0, Culture=neutral, PublicKeyToken=5d8b90d52f46fda7'. ---> System.TypeLoadException: Could not load type'Npgsql.NpgsqlCommandBuilder' from assembly 'Npgsql, Version=3.1.2.0, Culture=neutral, PublicKeyToken=5d8b90d52f46fda7'.
   at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMarkHandle stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName, ObjectHandleOnStack type, ObjectHandleOnStack keepalive)
   at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName)
   at System.RuntimeType.GetType(String typeName, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMark& stackMark)
   at System.Type.GetType(String typeName, Boolean throwOnError)
   at Quartz.Util.ObjectUtils.ConvertValueIfNecessary(Type requiredType, Object newValue)
   at Quartz.Util.ObjectUtils.SetPropertyValue(Object target, String propertyName, Object value)
   at Quartz.Util.ObjectUtils.SetObjectProperties(Object obj, NameValueCollection props)
   --- End of inner exception stack trace ---
   at Quartz.Util.ObjectUtils.SetObjectProperties(Object obj, NameValueCollection props)
   at Quartz.Impl.AdoJobStore.Common.EmbeddedAssemblyResourceDbMetadataFactory.GetDbMetadata(String providerName)
   --- End of inner exception stack trace ---
   at Quartz.Impl.AdoJobStore.Common.EmbeddedAssemblyResourceDbMetadataFactory.GetDbMetadata(String providerName)
   at Quartz.Impl.AdoJobStore.Common.DbProvider.GetDbMetadata(String providerName)
   at Quartz.Impl.AdoJobStore.Common.DbProvider..ctor(String dbProviderName, String connectionString)
   at Quartz.Impl.StdSchedulerFactory.<Instantiate>d__66.MoveNext()]

**Comment by lahma** [comment]
Fixed via d3fe4060e323a5d87225119a540161f55f7b90d5 .
