### ISSUE TITLE
Checking if job exists in Quartz.NET randomly fails

### ISSUE THREAD

**Issue by EdRbt** [quartznet/quartznet#504]
### Expected behavior
Check if a job already exists in database, using Quartz.Impl.StdScheduler.CheckExists(JobKey jobKey) method.

### Actual behavior
It randomly fails with error "Couldn't commit ADO.NET transaction. Transaction not connected, or was disconnected". I can't find a situation where it always occurs.

### Steps to reproduce
Configuration : 
```
        ["quartz.jobStore.type"] = "Quartz.Impl.AdoJobStore.JobStoreTX, Quartz",
        ["quartz.jobStore.driverDelegateType"] = "Quartz.Impl.AdoJobStore.SqlServerDelegate, Quartz",
        ["quartz.jobStore.tablePrefix"] = "QRTZ_",
        ["quartz.jobStore.dataSource"] = "rubis",
        ["quartz.dataSource.rubis.connectionStringName"] = "RubisEntities",
        ["quartz.dataSource.rubis.provider"] = "SqlServer-20",
        ["quartz.jobStore.useProperties"] = "true",
        ["quartz.threadPool.threadCount"] = "20"
```
Stack trace : 
```
at Quartz.Impl.AdoJobStore.JobStoreSupport.CommitConnection(ConnectionAndTransactionHolder cth, Boolean openNewTransaction) in c:\projects\quartznet\src\Quartz\Impl\AdoJobStore\JobStoreSupport.cs:line 3403
   at Quartz.Impl.AdoJobStore.JobStoreSupport.ExecuteInNonManagedTXLock[T](String lockName, Func`2 txCallback, Func`3 txValidator) in c:\projects\quartznet\src\Quartz\Impl\AdoJobStore\JobStoreSupport.cs:line 3562
   at Quartz.Impl.AdoJobStore.JobStoreTX.ExecuteInLock[T](String lockName, Func`2 txCallback) in c:\projects\quartznet\src\Quartz\Impl\AdoJobStore\JobStoreTX.cs:line 76
   at Quartz.Impl.AdoJobStore.JobStoreSupport.ExecuteWithoutLock[T](Func`2 txCallback) in c:\projects\quartznet\src\Quartz\Impl\AdoJobStore\JobStoreSupport.cs:line 3418
   at Quartz.Impl.AdoJobStore.JobStoreSupport.CheckExists(JobKey jobKey) in c:\projects\quartznet\src\Quartz\Impl\AdoJobStore\JobStoreSupport.cs:line 1739
   at Quartz.Core.QuartzScheduler.CheckExists(JobKey jobKey) in c:\projects\quartznet\src\Quartz\Core\QuartzScheduler.cs:line 1399
   at Quartz.Impl.StdScheduler.CheckExists(JobKey jobKey) in c:\projects\quartznet\src\Quartz\Impl\StdScheduler.cs:line 354
```
```csharp
// scheduler and job configuration, SystemTime prefereably set to fixed point
```

**Comment by EdRbt** [comment]
I just encountered the same error here:
```
   at Quartz.Impl.AdoJobStore.JobStoreSupport.CommitConnection(ConnectionAndTransactionHolder cth, Boolean openNewTransaction) in c:\projects\quartznet\src\Quartz\Impl\AdoJobStore\JobStoreSupport.cs:line 3403
   at Quartz.Impl.AdoJobStore.JobStoreSupport.ExecuteInNonManagedTXLock[T](String lockName, Func`2 txCallback, Func`3 txValidator) in c:\projects\quartznet\src\Quartz\Impl\AdoJobStore\JobStoreSupport.cs:line 3562
   at Quartz.Impl.AdoJobStore.JobStoreSupport.ExecuteInNonManagedTXLock[T](String lockName, Func`2 txCallback) in c:\projects\quartznet\src\Quartz\Impl\AdoJobStore\JobStoreSupport.cs:line 3498
   at Quartz.Impl.AdoJobStore.JobStoreTX.ExecuteInLock[T](String lockName, Func`2 txCallback) in c:\projects\quartznet\src\Quartz\Impl\AdoJobStore\JobStoreTX.cs:line 76
   at Quartz.Impl.AdoJobStore.JobStoreSupport.ExecuteWithoutLock[T](Func`2 txCallback) in c:\projects\quartznet\src\Quartz\Impl\AdoJobStore\JobStoreSupport.cs:line 3418
   at Quartz.Impl.AdoJobStore.JobStoreSupport.GetTriggersForJob(JobKey jobKey) in c:\projects\quartznet\src\Quartz\Impl\AdoJobStore\JobStoreSupport.cs:line 1935
   at Quartz.Core.QuartzScheduler.GetTriggersOfJob(JobKey jobKey) in c:\projects\quartznet\src\Quartz\Core\QuartzScheduler.cs:line 1329
   at Quartz.Core.QuartzScheduler.DeleteJob(JobKey jobKey) in c:\projects\quartznet\src\Quartz\Core\QuartzScheduler.cs:line 806
   at Quartz.Impl.StdScheduler.DeleteJob(JobKey jobKey) in c:\projects\quartznet\src\Quartz\Impl\StdScheduler.cs:line 314
```

**Comment by lahma** [comment]
Can you check the SQL Server logs, I guess there something else going on here. The exception is quite generic and indicates there might be something wrong at that time with the SQL Server itself.

**Comment by EdRbt** [comment]
Actually I had the same database for quartz and my entities. I separated the two and now it works.

**Comment by lahma** [comment]
OK so it was a resource issue, good that you got that sorted out.
