### ISSUE TITLE
Support Microsoft.Data.Sqlite provider on .NET Core 

### ISSUE THREAD

**Issue by manfromcoimbatore** [quartznet/quartznet#517]
Using Version: 3.0.0-alpha3

Trying to use Sqlite with Quartz scheduler with System.Data.Sqlite.Core (1.0.105.2) with the following configuration:

NameValueCollection props = new NameValueCollection
                {
					//{ "quartz.serializer.type", "binary" },
                    { "quartz.threadPool.type", "Quartz.Simpl.SimpleThreadPool, Quartz" },
                    { "quartz.threadPool.threadCount", "10" },
                    { "quartz.jobStore.type", "Quartz.Impl.AdoJobStore.JobStoreTX, Quartz" },
                    { "quartz.jobStore.misfireThreshold", "60000" },
                    { "quartz.jobStore.lockHandler.type", "Quartz.Impl.AdoJobStore.UpdateLockRowSemaphore, Quartz" },
                    { "quartz.jobStore.useProperties", "true" },
                    { "quartz.jobStore.dataSource", "default" },
                    { "quartz.jobStore.tablePrefix", "QRTZ_" },
                    { "quartz.jobStore.driverDelegateType", "Quartz.Impl.AdoJobStore.SQLiteDelegate, Quartz" },
                    { "quartz.dataSource.default.provider", "SQLite-10" },
                    { "quartz.dataSource.default.connectionString", "Data Source=quartznet.db;Version=3;" }

                };

### Actual behavior

Quartz.SchedulerException: Could not Initialize DataSource: SqliteDS ---> System.ArgumentOutOfRangeException: **There is no metadata information for provider 'SQLite-10'**
Parameter name: providerName
   at Quartz.Impl.AdoJobStore.Common.DbProvider.GetDbMetadata(String providerName) in C:\projects\quartznet-6fcn8\src\Quartz\Impl\AdoJobStore\Common\DbProvider.cs:line 118
   at Quartz.Impl.AdoJobStore.Common.DbProvider..ctor(String dbProviderName, String connectionString) in C:\projects\quartznet-6fcn8\src\Quartz\Impl\AdoJobStore\Common\DbProvider.cs:line 74
   at Quartz.Impl.StdSchedulerFactory.<Instantiate>d__65.MoveNext() in C:\projects\quartznet-6fcn8\src\Quartz\Impl\StdSchedulerFactory.cs:line 614
   --- End of inner exception stack trace ---
   at Quartz.Impl.StdSchedulerFactory.<Instantiate>d__65.MoveNext() in C:\projects\quartznet-6fcn8\src\Quartz\Impl\StdSchedulerFactory.cs:line 623
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Quartz.Impl.StdSchedulerFactory.<GetScheduler>d__69.MoveNext() in C:\projects\quartznet-6fcn8\src\Quartz\Impl\StdSchedulerFactory.cs:line 1118
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at BackgroundProcessingWithQuartz.Program.<RunProgram>d__1.MoveNext() in /Users/Projects/BackgroundProcessingWithQuartz/BackgroundProcessingWithQuartz/BackgroundProcessingWithQuartz/Program.cs:line 44 [See nested exception: System.ArgumentOutOfRangeException: There is no metadata information for provider 'SQLite-10'
Parameter name: providerName
   at Quartz.Impl.AdoJobStore.Common.DbProvider.GetDbMetadata(String providerName) in C:\projects\quartznet-6fcn8\src\Quartz\Impl\AdoJobStore\Common\DbProvider.cs:line 118
   at Quartz.Impl.AdoJobStore.Common.DbProvider..ctor(String dbProviderName, String connectionString) in C:\projects\quartznet-6fcn8\src\Quartz\Impl\AdoJobStore\Common\DbProvider.cs:line 74
   at Quartz.Impl.StdSchedulerFactory.<Instantiate>d__65.MoveNext() in C:\projects\quartznet-6fcn8\src\Quartz\Impl\StdSchedulerFactory.cs:line 614

### Steps to reproduce

What I am missing? Everything is installed through NuGet on my Visual Studio for Mac. Plus why are there are references to the C Drive when the dll is actually running on a Mac. Please help. 

```csharp
// scheduler and job configuration, SystemTime prefereably set to fixed point
```

**Comment by lahma** [comment]
It seems that the current official driver does not support .NET Core. Microsoft's version however seems to support .NET Standard 2.0. We can probably add support for Microsoft's version.

**Comment by manfromcoimbatore** [comment]
Thank you for the prompt follow up on this matter. Any chance I have a work around on this in the meanwhile? What packages should I be using in my .Net core app to support Sqlite ado job store. Thanks again!

**Comment by lahma** [comment]
Sorry for the delay, here's an example I quickly put together, your mileage might vary. NET Core 2.0 console app referencing required libs

```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" Version="2.0.0" />
    <PackageReference Include="Quartz" Version="3.0.0-alpha3" />
  </ItemGroup>
</Project>

```
```
using System;
using System.Collections.Specialized;
using System.Data;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Data.Sqlite;
using Quartz;
using Quartz.Impl;
using Quartz.Impl.AdoJobStore.Common;

namespace ConsoleApplication1
{
    class Program
    {
        static void Main()
        {
            Run().GetAwaiter().GetResult();
        }

        private static async Task Run()
        {
            DbProvider.RegisterDbMetadata("sqlite-custom", new DbMetadata()
            {
                AssemblyName = typeof(SqliteConnection).Assembly.GetName().Name,
                ConnectionType = typeof(SqliteConnection),
                CommandType = typeof(SqliteCommand),
                ParameterType = typeof(SqliteParameter),
                ParameterDbType = typeof(DbType),
                ParameterDbTypePropertyName = "DbType",
                ParameterNamePrefix = "@",
                ExceptionType = typeof(SqliteException),
                BindByName = true
            });


            var properties = new NameValueCollection
            {
                ["quartz.jobStore.type"] = "Quartz.Impl.AdoJobStore.JobStoreTX, Quartz",
                ["quartz.jobStore.useProperties"] = "true",
                ["quartz.jobStore.dataSource"] = "default",
                ["quartz.jobStore.tablePrefix"] = "QRTZ_",
                ["quartz.jobStore.driverDelegateType"] = "Quartz.Impl.AdoJobStore.SQLiteDelegate, Quartz",
                ["quartz.dataSource.default.provider"] = "sqlite-custom",
                ["quartz.dataSource.default.connectionString"] = "Data Source=test.db",
                ["quartz.jobStore.lockHandler.type"] = "Quartz.Impl.AdoJobStore.UpdateLockRowSemaphore, Quartz",
                ["quartz.serializer.type"] = "binary"
            };


            ISchedulerFactory sf = new StdSchedulerFactory(properties);
            IScheduler sched = await sf.GetScheduler();

            await sched.Start();

            Thread.Sleep(TimeSpan.FromMinutes(10));
        }
    }
}
```

**Comment by raffaeler** [comment]
@lahma I tried this solution but get:
```
SQLite Error 1: 'no such table: QRTZ_LOCKS'.
```
which of course is true since the database still does not exist. Should I create it before? How?
TIA

**Comment by lahma** [comment]
You need to create tables before you can use the database. You can see my test case as part of the commit [here](https://github.com/quartznet/quartznet/commit/5ce19e6a79daa967890b93ed254ee6528e2aee2e#diff-7f520fc73a3283429dd24c4d1d61112fR94). 

You probably want to run creation scripts if the file didn't exist before and thus database requires fresh start.

**Comment by raffaeler** [comment]
Got it, thanks. As I am not familiar with this project, I had no idea of the scripts.
