### ISSUE TITLE
XMLSchedulingDataProcessor OverWriteExistingData is ignored?

### ISSUE THREAD

**Issue by meetakherdekar** [quartznet/quartznet#559]
### Expected behavior
I assumed that if I set XMLSchedulingDataProcessor.OverWriteExistingData to false; if the job already exists; it will not attempt to create a new one.

Instead; it attempts to create one and throws error in log - 
Could not schedule jobs and triggers from file <fileName>: Unable to store Job: <jobname>, because one already exists with this identification.
Quartz.ObjectAlreadyExistsException: Unable to store Job: <jobName>, because one already exists with this identification.
   at Quartz.Xml.XMLSchedulingDataProcessor.<ScheduleJobs>d__53.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Quartz.Xml.XMLSchedulingDataProcessor.<ProcessFileAndScheduleJobs>d__51.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```
Any suggestions; how I can avoid this error ?

**Comment by lahma** [comment]
You should try setting the configuration option [ignore-duplicates](https://github.com/quartznet/quartznet/blob/master/src/Quartz/Xml/job_scheduling_data_2_0.xsd#L86).
