### ISSUE TITLE
The element 'simple' has invalid child element 'repeat-interval'. List of possible elements expected: 'repeat-count'

### ISSUE THREAD

**Issue by Valeriy1991** [quartznet/quartznet#563]
Hi!

I have quartz_jobs.xml file for configuring my jobs. I have simple LogJob class:
```
    public class LogJob : IJob
    {
        private readonly ILogger _logger;

        public LogJob(ILogger<LogJob> logger)
        {
            if (logger == null)
                throw new ArgumentNullException(nameof(logger));
            _logger = logger;
        }

        public Task Execute(IJobExecutionContext context)
        {
            return Task.Run(() =>
            {
                var jobId = context.FireInstanceId;
                var jobName = context.JobDetail.Key.Name;

                _logger.LogInformation($"[{jobId}] {jobName} - job is work");
            });
        }
    }
```
My quartz_jobs.xml is:
```
<?xml version="1.0" encoding="utf-8" ?>
<job-scheduling-data xmlns="http://quartznet.sourceforge.net/JobSchedulingData" 
                     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="2.0">
 
  <processing-directives>
    <overwrite-existing-data>true</overwrite-existing-data>
  </processing-directives>
 
  <schedule>
 
    <job>
      <name>LogJob</name>
      <group>LogJob_Group</group>
      <description>Задание для теста - пишет в логи сообщение "Job is work"</description>
      <job-type>Scheduler.Quartz.Jobs.LogJob, Scheduler.Quartz</job-type>
      <durable>true</durable>
      <recover>false</recover>
    </job>
 
    <trigger>
      <simple>
        <name>LogJob_SimpleTrigger</name>
        <job-name>LogJob</job-name>
        <job-group>LogJob_Group</job-group>
        <misfire-instruction>SmartPolicy</misfire-instruction>
        <!-- In version 3.0.0-beta1 and 3.0.0-alpha3 this is required??? -->
        <!--<repeat-count>-1</repeat-count>-->
        <repeat-interval>10000</repeat-interval>
      </simple>
      
    </trigger>
 
  </schedule>
 
</job-scheduling-data>
```

### Expected behavior
LogJob must started every 10 sec.

### Actual behavior
In my logs that stored in MS SQL Server (I'm use NLog) I see that Quartz.NET has logged an exception:
```
Quartz.Xml.ValidationException: The element 'simple' in namespace 'http://quartznet.sourceforge.net/JobSchedulingData' has invalid child element 'repeat-interval' in namespace 'http://quartznet.sourceforge.net/JobSchedulingData'. List of possible elements expected: 'repeat-count' in namespace 'http://quartznet.sourceforge.net/JobSchedulingData'.  
at Quartz.Xml.XMLSchedulingDataProcessor.MaybeThrowValidationException()
at Quartz.Xml.XMLSchedulingDataProcessor.ProcessInternal(String xml)
at Quartz.Xml.XMLSchedulingDataProcessor.<ProcessFile>d__36.MoveNext()  --- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Quartz.Xml.XMLSchedulingDataProcessor.<ProcessFileAndScheduleJobs>d__51.MoveNext()  --- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Quartz.Plugin.Xml.XMLSchedulingDataProcessorPlugin.<ProcessFile>d__45.MoveNext()
```
and logged this message:
```
Could not schedule jobs and triggers from file quartz_jobs.xml: The element 'simple' in namespace 'http://quartznet.sourceforge.net/JobSchedulingData' has invalid child element 'repeat-interval' in namespace 'http://quartznet.sourceforge.net/JobSchedulingData'. List of possible elements expected: 'repeat-count' in namespace 'http://quartznet.sourceforge.net/JobSchedulingData'.  
```
But if I'm will uncomment this line in quartz_jobs.xml:
```
<!--<repeat-count>-1</repeat-count>-->
```
then Quartz.NET run my LogJob every 10 sec as I'm expected.

Note that in version 3.0.0-alpha2 this exception was not thrown, and missing of the tag 'repeat-count' did not result on this error (but in version 3.0.0-alpha3 Quartz.NET throw the same exception as in the 3.0.0-beta1).

P.S. I'm not found info about that the 'repeat-count' tag is required.

**Comment by lahma** [comment]
Yes the repeat-count is indeed required. alpha2 just didn't validate the XML properly and later versions are again validating as expected. The schema states that it's mandatory:

https://github.com/quartznet/quartznet/blob/master/src/Quartz/Xml/job_scheduling_data_2_0.xsd#L177

**Comment by CallMeMT** [comment]
I used the Quartz 3.04 and Quartz.Plugins 3.04 in NuGet. But there has an exception

- Could not schedule jobs and triggers from file quartz_jobs.xml: The element 'simple' in namespace 'http://quartznet.sourceforge.net/JobSchedulingData' has invalid child element 'repeat-interval' in namespace 'http://quartznet.sourceforge.net/JobSchedulingData'. List of possible elements expected: 'repeat-count' in namespace 'http://quartznet.sourceforge.net/JobSchedulingData'.  

-
![image](https://user-images.githubusercontent.com/8121083/40042642-b135c2e2-5854-11e8-9be0-830b959813bf.png)
