### ISSUE TITLE
AdoJobStore  throws exception in MySql 5.7

### ISSUE THREAD

**Issue by c0pp3rt0p** [quartznet/quartznet#602]
### Version:
Quart v. 2.6.1

### Expected behavior
I expect the ado.functionality to work with MySQL 5.7.  I understand that 5.7 isn't currently listed as a supported version yet as well, 

I haven't re-run the sql script to generate the tables yet, so maybe re-running that might alleviate this issue.

### Actual behavior

While attempting to get triggers of a jobJey the following exception is thrown.

Quartz.JobPersistenceException
  HResult=0x80131500
  Message=Couldn't obtain triggers for job: Binary stream '0' does not contain a valid BinaryHeader. Possible causes are invalid stream or object version change between serialization and deserialization.
  Source=Quartz
  StackTrace:
   at Quartz.Impl.AdoJobStore.JobStoreSupport.GetTriggersForJob(ConnectionAndTransactionHolder conn, JobKey jobKey)
   at Quartz.Impl.AdoJobStore.JobStoreSupport.ExecuteInNonManagedTXLock[T](String lockName, Func`2 txCallback, Func`3 txValidator)
   at Quartz.Impl.AdoJobStore.JobStoreSupport.ExecuteInNonManagedTXLock[T](String lockName, Func`2 txCallback)
   at Quartz.Core.QuartzScheduler.GetTriggersOfJob(JobKey jobKey)
   at JMS.JobManager.UnscheduleAllTriggersForJobKey(JobKey jobKey) in D:\GitRepository\JMS\JMS\JMS\Job Manager\JobManager.cs:line 172
   at JMS.JobManager.CreateAllJobs() in D:\GitRepository\JMS\JMS\JMS\Job Manager\JobManager.cs:line 118
   at JMS.JobManager.Init() in D:\GitRepository\JMS\JMS\JMS\Job Manager\JobManager.cs:line 76
   at JMS.DocLogicJMS.StartService() in D:\GitRepository\JMS\JMS\JMS\JMSService.cs:line 41
   at JMS.Program.Main(String[] args) in D:\GitRepository\JMS\JMS\JMS\Program.cs:line 48

Inner Exception 1:
SerializationException: Binary stream '0' does not contain a valid BinaryHeader. Possible causes are invalid stream or object version change between serialization and deserialization.

### Steps to reproduce

1. Upgrade existing MySQL database from 5.5 to 5.7
2. Perform a scheduler.GetTriggersOfJob([validJobKey])

**Comment by c0pp3rt0p** [comment]
Blew away the quartz tables and re-ran, the script on the 5.7 instance and it works fine.  Not a great solution for anyone else out there who has scheduled jobs.  This all could be an artifact of the upgrade process.
