### ISSUE TITLE
Quartz 3.0.5 not able to recover from DB connection drops

### ISSUE THREAD

**Issue by j03wang** [quartznet/quartznet#637]
### Expected behavior

I'm using Quartz with the SqlServer jobstore connecting to an Azure SQL database. There are occasions when the connection will have hiccups, for which I'm expecting Quartz to be able to handle and reconnect. 

### Actual behavior

I was using Quartz 2.x previously and everything was working fine, but since upgrading to Quartz 3.0.5 (now using .NET Core), I'm seeing either single triggers stalling with log messages `ConnectionAndTransactionHolder passed to RollbackConnection was null, ignoring` and these kinds of messages when querying the scheduler for triggers:

``Quartz.JobPersistenceException: Failed to obtain DB connection from data source 'ds': System.InvalidOperationException: Timeout expired.  The timeout period elapsed prior to obtaining a connection from the pool.  This may have occurred because all pooled connections were in use and max pool size was reached.
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal&amp; connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at Quartz.Impl.AdoJobStore.JobStoreSupport.GetConnection() ---> System.InvalidOperationException: Timeout expired.  The timeout period elapsed prior to obtaining a connection from the pool.  This may have occurred because all pooled connections were in use and max pool size was reached.
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at Quartz.Impl.AdoJobStore.JobStoreSupport.GetConnection()
   --- End of inner exception stack trace ---
   at Quartz.Impl.AdoJobStore.JobStoreSupport.GetConnection()
   at Quartz.Impl.AdoJobStore.JobStoreSupport.ExecuteInNonManagedTXLock[T](String lockName, Func`2 txCallback, Func`3 txValidator, CancellationToken cancellationToken)
   at Quartz.Impl.AdoJobStore.JobStoreSupport.ExecuteInNonManagedTXLock[T](String lockName, Func`2 txCallback, Func`3 txValidator, CancellationToken cancellationToken)``

### Steps to reproduce

I haven't explicitly made a repro, but here's my configuration. I'm running very simple jobs on a minute basis. I'm guessing you can get a repro just by severing the db connection while Quartz is running.

```csharp
{
    { "quartz.jobStore.type", "Quartz.Impl.AdoJobStore.JobStoreTX, Quartz" },
    { "quartz.jobStore.driverDelegateType", "Quartz.Impl.AdoJobStore.SqlServerDelegate, Quartz" },
    { "quartz.jobStore.tablePrefix", "QRTZ_" },
    { "quartz.jobStore.dataSource", "ds" },
    { "quartz.dataSource.ds.connectionString", "<connection string>" },
    { "quartz.dataSource.ds.provider", "SqlServer" },
    { "quartz.jobStore.useProperties", "true" },
    { "quartz.threadPool.threadCount", "20" },
    { "quartz.serializer.type", "json" }
}
```

**Comment by lahma** [comment]
Thanks for reporting the issue with details.

This seems to be a bug in System.Data.SqlClient package. You can update your local package to latest version 4.5.1 and that should fix the hang you are seeing. I've upgraded the package for 3.0.6 release.
