### ISSUE TITLE
Quartz job recovery periodically fails in clustered environment

### ISSUE THREAD

**Issue by eugentorica** [quartznet/quartznet#67]
Using Quartz 2.0.1 SqlSever with mirroring.

quartz.jobStore.type = "Quartz.Impl.AdoJobStore.JobStoreTX, Quartz";
quartz.jobStore.clustered = "true";
quartz.jobStore.lockHandler.type = "Quartz.Impl.AdoJobStore.UpdateLockRowSemaphore, Quartz";

Sometimes one sql server instance fails and I find in log error of this kind:

[ERROR] Quartz.Core.QuartzSchedulerThread - Runtime error occurred in main trigger firing loop.
System.ArgumentNullException: Connnection-transaction pair cannot be null
Parameter name: cth
 at Quartz.Impl.AdoJobStore.JobStoreSupport.RollbackConnection(ConnectionAndTransactionHolder cth) in c:\Work\OpenSource\quartznet\src\Quartz\Impl\AdoJobStore\JobStoreSupport.cs:line 3300
   at Quartz.Impl.AdoJobStore.JobStoreSupport.ExecuteInNonManagedTXLock(String lockName, Func`2 txCallback) in c:\Work\OpenSource\quartznet\src\Quartz\Impl\AdoJobStore\JobStoreSupport.cs:line 3463
   at Quartz.Impl.AdoJobStore.JobStoreSupport.TriggersFired(IList`1 triggers) in c:\Work\OpenSource\quartznet\src\Quartz\Impl\AdoJobStore\JobStoreSupport.cs:line 2550
   at Quartz.Core.QuartzSchedulerThread.Run() in c:\Work\OpenSource\quartznet\src\Quartz\Core\QuartzSchedulerThread.cs:line 369
    DateTime=2012-09-18T19:27:29.0470000Z

After this message I assume job gets blocked and in logs with certain periodicity appears the following message:
Quartz.Impl.AdoJobStore.JobStoreTX - Handling 1 trigger(s) that missed their scheduled fire-time.

I suppose that this is an attempt to handle blocked job but for now I have to wait when job gets blocked and see the dump.
Other jobs (about 25) works as expected. By blocked I mean that job is not fired. 

Blocked trigger has state ACQUIRED in table TRIGGERS . This trigger also appears in FIRED_TRIGGERS table with state ACQUIRED. Interestingly value of NEXT_FIRE_TIME field in TRIGGERS table for this trigger is constantly increasing although job is not called.

Service is stopping normally so I assume no job thread gets blocked in this scenario however restarting service does not help. All triggers start working normally beside blocked one.

Solution is to reset manually trigger's state to WAITING in TRIGGERS table.

**Comment by ndenkha** [comment]
Hi guys, I'm on Quartz 2.3.3 in a clustered mode between two instances of the same scheduler, and this setup has been running fine for years and only today we've started getting this same exception. And our Quartz DB is on SQL Server 2014. There're are no SQL errors. Any ideas what's started causing this? Is this bug still not fixed in 2.3.3 and the cause is SQL Server's hourly backup jobs? Please advise.

2018-02-12 11:29:05,848 [ProcessorScheduler_QuartzSchedulerThread] ERROR  Quartz.Impl.AdoJobStore.JobStoreTX - Couldn't rollback ADO.NET connection. Transaction not connected, or was disconnected System.Data.DataException: Transaction not connected, or was disconnected
   at Quartz.Impl.AdoJobStore.JobStoreSupport.CheckNotZombied(ConnectionAndTransactionHolder cth) in c:\Program Files (x86)\Jenkins\workspace\Quartz.NET\src\Quartz\Impl\AdoJobStore\JobStoreSupport.cs:line 3580
   at Quartz.Impl.AdoJobStore.JobStoreSupport.RollbackConnection(ConnectionAndTransactionHolder cth) in c:\Program Files (x86)\Jenkins\workspace\Quartz.NET\src\Quartz\Impl\AdoJobStore\JobStoreSupport.cs:line 3353

2018-02-12 11:29:05,864 [ProcessorScheduler_QuartzSchedulerThread] ERROR  Quartz.Core.ErrorLogger - An error occurred while scanning for the next trigger to fire. Quartz.JobPersistenceException: Couldn't acquire next trigger: Transaction (Process ID 90) was deadlocked on lock resources with another process and has been chosen as the deadlock victim. Rerun the transaction. ---> System.Data.SqlClient.SqlException: Transaction (Process ID 90) was deadlocked on lock resources with another process and has been chosen as the deadlock victim. Rerun the transaction.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryHasMoreRows(Boolean& moreRows)
   at System.Data.SqlClient.SqlDataReader.TryReadInternal(Boolean setTimeout, Boolean& more)
   at System.Data.SqlClient.SqlDataReader.Read()
   at Quartz.Impl.AdoJobStore.StdAdoDelegate.SelectTriggerToAcquire(ConnectionAndTransactionHolder conn, DateTimeOffset noLaterThan, DateTimeOffset noEarlierThan, Int32 maxCount) in c:\Program Files (x86)\Jenkins\workspace\Quartz.NET\src\Quartz\Impl\AdoJobStore\StdAdoDelegate.cs:line 2241
   at Quartz.Impl.AdoJobStore.JobStoreSupport.AcquireNextTrigger(ConnectionAndTransactionHolder conn, DateTimeOffset noLaterThan, Int32 maxCount, TimeSpan timeWindow) in c:\Program Files (x86)\Jenkins\workspace\Quartz.NET\src\Quartz\Impl\AdoJobStore\JobStoreSupport.cs:line 2465
   --- End of inner exception stack trace ---
   at Quartz.Impl.AdoJobStore.JobStoreSupport.AcquireNextTrigger(ConnectionAndTransactionHolder conn, DateTimeOffset noLaterThan, Int32 maxCount, TimeSpan timeWindow) in c:\Program Files (x86)\Jenkins\workspace\Quartz.NET\src\Quartz\Impl\AdoJobStore\JobStoreSupport.cs:line 2546
   at Quartz.Impl.AdoJobStore.JobStoreSupport.<>c__DisplayClass66.<AcquireNextTriggers>b__64(ConnectionAndTransactionHolder conn) in c:\Program Files (x86)\Jenkins\workspace\Quartz.NET\src\Quartz\Impl\AdoJobStore\JobStoreSupport.cs:line 2417
   at Quartz.Impl.AdoJobStore.JobStoreSupport.ExecuteInNonManagedTXLock[T](String lockName, Func`2 txCallback, Func`3 txValidator) in c:\Program Files (x86)\Jenkins\workspace\Quartz.NET\src\Quartz\Impl\AdoJobStore\JobStoreSupport.cs:line 3551
   at Quartz.Impl.AdoJobStore.JobStoreSupport.AcquireNextTriggers(DateTimeOffset noLaterThan, Int32 maxCount, TimeSpan timeWindow) in c:\Program Files (x86)\Jenkins\workspace\Quartz.NET\src\Quartz\Impl\AdoJobStore\JobStoreSupport.cs:line 2416
   at Quartz.Core.QuartzSchedulerThread.Run() in c:\Program Files (x86)\Jenkins\workspace\Quartz.NET\src\Quartz\Core\QuartzSchedulerThread.cs:line 253 [See nested exception: System.Data.SqlClient.SqlException (0x80131904): Transaction (Process ID 90) was deadlocked on lock resources with another process and has been chosen as the deadlock victim. Rerun the transaction.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryHasMoreRows(Boolean& moreRows)
   at System.Data.SqlClient.SqlDataReader.TryReadInternal(Boolean setTimeout, Boolean& more)
   at System.Data.SqlClient.SqlDataReader.Read()
   at Quartz.Impl.AdoJobStore.StdAdoDelegate.SelectTriggerToAcquire(ConnectionAndTransactionHolder conn, DateTimeOffset noLaterThan, DateTimeOffset noEarlierThan, Int32 maxCount) in c:\Program Files (x86)\Jenkins\workspace\Quartz.NET\src\Quartz\Impl\AdoJobStore\StdAdoDelegate.cs:line 2241
   at Quartz.Impl.AdoJobStore.JobStoreSupport.AcquireNextTrigger(ConnectionAndTransactionHolder conn, DateTimeOffset noLaterThan, Int32 maxCount, TimeSpan timeWindow) in c:\Program Files (x86)\Jenkins\workspace\Quartz.NET\src\Quartz\Impl\AdoJobStore\JobStoreSupport.cs:line 2465
ClientConnectionId:f756de7b-1a1c-45ee-9045-e276b064d55e
Error Number:1205,State:51,Class:13]

**Comment by lahma** [comment]
@ndenkha I'd suspect your DB has grown in size or your host is running out of resources. As stated before you should check the backup schedule and DB configuration. Running newer version of Quartz never hurts but requires small DB migration script to run. But the underlying issue probably won't be fixed with upgrade.

Hourly backup seems quite often...
