### ISSUE TITLE
Custom calendars can no longer be serialized.

### ISSUE THREAD

**Issue by mjwires** [quartznet/quartznet#697]
### Version: x.y.z
Versions 3.0.6 and 3.0.7

### Expected behavior
I'm attempting to add my own custom calendar that inherits from Quartz.Impl.Calendar.BaseCalendar via IScheduler.AddCalendar. This works fine in 3.0.5 and earlier versions.

### Actual behavior
Calling AddCalendar now results in the following error:

Quartz.JobPersistenceException: Couldn't store calendar: don't know how to handle [MY TYPE NAME] ---> System.ArgumentException: don't know how to handle [MY TYPE NAME]
at Quartz.Simpl.JsonObjectSerializer.CalendarConverter.GetCalendarConverter(String typeName)
at Quartz.Simpl.JsonObjectSerializer.CalendarConverter.WriteJson(JsonWriter writer, Object value, JsonSerializer serializer)
at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeConvertable(JsonWriter writer, JsonConverter converter, Object value, JsonContract contract, JsonContainerContract collectionContract, JsonProperty containerProperty)
at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
at Quartz.Simpl.JsonObjectSerializer.Serialize[T](T obj)
at Quartz.Impl.AdoJobStore.StdAdoDelegate.SerializeObject(Object obj)
at Quartz.Impl.AdoJobStore.StdAdoDelegate.<InsertCalendar>d__93.MoveNext()

**Comment by lahma** [comment]
So probably either https://github.com/quartznet/quartznet/issues/634 or https://github.com/quartznet/quartznet/issues/621 surfaced this. Can you build a failing test case for investigation?

**Comment by lahma** [comment]
Closing due to inactivity, can be if/when new info appears.

**Comment by mjwires** [comment]
Attaching a test project that demonstrates the problem.
[quartz_697.zip](https://github.com/quartznet/quartznet/files/3854452/quartz_697.zip)

**Comment by lahma** [comment]
I've enabled added support for custom calendar serializers. You need to implement one for your calendar, [here are the docs](https://www.quartz-scheduler.net/documentation/quartz-3.x/packages/json-serialization.html#customizing-calendar-serialization).

**Comment by mjwires** [comment]
Is this intended to be compatible with custom calendars that were already serialized and working in 3.0.5? I made the changes listed in that link (Built a CalendarSerializer and registered it using JsonObjectSerializer.AddCalendarSerializer. My CustomCalendar was already implemented as suggested.) And now I receive the following error in my log: "Caught job persistence exception: Couldn't retrieve calendar: Value cannot be null."

**Comment by lahma** [comment]
This would require more information and better stack traces. Maybe you could debug the problem and share some insights?

**Comment by mjwires** [comment]
The full stack trace:

Caught job persistence exception: Couldn't retrieve calendar: Value cannot be null.
Parameter name: value
   at Newtonsoft.Json.Linq.Extensions.Value[T,U](IEnumerable`1 value)
   at Quartz.Converters.CalendarConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Quartz.Simpl.JsonObjectSerializer.DeSerialize[T](Byte[] obj)
   at Quartz.Impl.AdoJobStore.StdAdoDelegate.<GetObjectFromBlob>d__128`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Quartz.Impl.AdoJobStore.StdAdoDelegate.<SelectCalendar>d__99.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Quartz.Impl.AdoJobStore.JobStoreSupport.<RetrieveCalendar>d__185.MoveNext()

All constructors and (de)serialization methods in my calendar and calendar serializer classes have their own exception handling and logging, and I'm not getting any errors there, so I don't think it's getting to that point.

Here's one of the entries from the CALENDAR column in my QRTZ_CALENDARS table that Quartz is failing to deserialize:

{"$type":"MY_TYPE_NAME, MY_ASSEMBLY_NAME","ExcludeWeekends":true,"ExcludeDateList":{"$type":"System.Collections.Generic.List`1[[System.DateTime, mscorlib]], mscorlib","$values":[]},"TimeZone":{"$type":"System.TimeZoneInfo, mscorlib","Id":"Eastern Standard Time","DisplayName":"(UTC-05:00) Eastern Time (US & Canada)","StandardName":"Eastern Standard Time","DaylightName":"Eastern Daylight Time","BaseUtcOffset":"-05:00:00","SupportsDaylightSavingTime":true}}'

ExcludeWeekends and ExcludeDateList are my two custom properties. Is there anything missing that might be causing the failure?

**Comment by lahma** [comment]
Looking at the JSON it doesn't look like it contains the data that calendars have (hence the bug that this was broken for custom calendars). Looking at code paths I would expect that you have your own calendar derived from `CalendarBase`? This would confuse the logic to think that it will find the fields it expects:

```
            if (calendar is BaseCalendar target)
            {
                target.Description = jObject["Description"]!.Value<string>();
                target.TimeZone = TimeZoneUtil.FindTimeZoneById(jObject["TimeZoneId"]!.Value<string>());
                var baseCalendar = jObject["BaseCalendar"]!.Value<JObject>();
                if (baseCalendar != null)
                {
                    var baseCalendarType = Type.GetType(baseCalendar["$type"]!.Value<string>(), true);
                    var o = baseCalendar.ToObject(baseCalendarType!, serializer);
                    target.CalendarBase = (ICalendar?) o;
                }
            }
```

I think that you could get this working by removing inheritance from BaseCalendar and then handling the fields manually. Ideally your reader/writer would also support two modes by detecting that TimeZone or TimeZoneId is there, I would think that you would want only to persist the ID like the current logic does for Quartz's calendars.
