### ISSUE TITLE
Could not load file or assembly Quartz, Version=3.0.7.0 when use netcore2.1 deploy on IIS

### ISSUE THREAD

**Issue by runtop** [quartznet/quartznet#717]
Version: 3.0.7

develop environment in asp.net core 2.1

all work fine when i debug the project in vs2017, and also  worked in console by execute "dotnet xxx.web.dll "
but when i publish the project to windows 2012 server and using IIS,  it's report that :

Application startup exception: System.IO.FileNotFoundException: Could not load file or assembly 'Quartz, Version=3.0.7.0, Culture=neutral, PublicKeyToken=f6b8c98a402cc8a4'. 系统找不到指定的文件。
File name: 'Quartz, Version=3.0.7.0, Culture=neutral, PublicKeyToken=f6b8c98a402cc8a4'
   at System.Signature.GetSignature(Void* pCorSig, Int32 cCorSig, RuntimeFieldHandleInternal fieldHandle, IRuntimeMethodInfo methodHandle, RuntimeType declaringType)
   at System.Reflection.RuntimeMethodInfo.get_ReturnType()
   at Microsoft.AspNetCore.Hosting.Internal.StartupLoader.FindMethod(Type startupType, String methodName, String environmentName, Type returnType, Boolean required)
   at Microsoft.AspNetCore.Hosting.Internal.StartupLoader.FindConfigureDelegate(Type startupType, String environmentName)
   at Microsoft.AspNetCore.Hosting.Internal.StartupLoader.LoadMethods(IServiceProvider hostingServiceProvider, Type startupType, String environmentName)
   at Microsoft.AspNetCore.Hosting.WebHostBuilderExtensions.<>c__DisplayClass1_0.<UseStartup>b__1(IServiceProvider sp)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitSingleton(SingletonCallSite singletonCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureStartup()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.Initialize()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()

### Steps to reproduce

```csharp
public void ConfigureServices(IServiceCollection services) {
    services.AddSingleton<ISchedulerFactory, StdSchedulerFactory>();
    IScheduler scheduler = services.BuildServiceProvider().GetService<ISchedulerFactory>().GetScheduler().Result;
   services.AddSingleton<IScheduler>(scheduler);

...
}


```

**Comment by lahma** [comment]
Do you have Quartz.dll in the IIS directory where you have the xx.web.dll?

**Comment by runtop** [comment]
> Do you have Quartz.dll in the IIS directory where you have the xx.web.dll?

Of course，the Quartz.dll is in the same directory with xx.web.dll .

I used vs2017  , and publish the web project to a directory,  then I open a CMD console , location to the directory , executed 'dotnet xx.web.dll' , it will listen default 5000 port and start the quartz's schedule. The web project worked fine.  but when I use IIS, create a website in IIS and map to the proejct's directory,  it will throw the exception "Could not load the file ".  When I remove all code about quartz ,the website can work fine.

I think has it maybe some wrong working directory environment and can not find correspond file when it under IIS ?
