### ISSUE TITLE
AggregateException&JobPersistenceException: ScheduleJob failed, with JobStoreTX use MySql

### ISSUE THREAD

**Issue by YoungL1107** [quartznet/quartznet#737]
### Version: 3.0.7
ASP.NET Core Web Application (2.1)
Quartz (3.0.7)
Quartz.Serialization.Json (3.0.7)

### Expected behavior
expect to store JobData into MySql Db, when it works fine in SqlServer .
### Actual behavior

System.AggregateException
  HResult=0x80131500
  Message=One or more errors occurred.
  Source=System.Private.CoreLib
  StackTrace:
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at QuartZWeb.Startup.CreateScheduler() in C:\Users\Young\source\repos\Young.Lab\QuartZWeb\Startup.cs:line 173
   at QuartZWeb.Startup.ConfigureServices(IServiceCollection services) in C:\Users\Young\source\repos\Young.Lab\QuartZWeb\Startup.cs:line 42

innerException 1:
JobPersistenceException: Couldn't store job: Object reference not set to an instance of an object.

innerException 2:
NullReferenceException: Object reference not set to an instance of an object.

### Steps to reproduce

```csharp
            DBConnectionManager.Instance.AddConnectionProvider("MySql", new DbProvider("MySql", "Database=xxxxx;Data Source=xxxxx;User Id=xxxx;Password=xxxxx;pooling=false;CharSet=utf8;port=3306"));

            var jobStore = new JobStoreTX {
                DataSource= "MySql",
                InstanceId= schedulerId,
                TablePrefix= "QRTZ_",
                DriverDelegateType = typeof(MySQLDelegate).AssemblyQualifiedName,
                ObjectSerializer = new JsonObjectSerializer(),
                Clustered = true,
                ClusterCheckinInterval = TimeSpan.FromMilliseconds(3000)
            };

            DirectSchedulerFactory.Instance.CreateScheduler(schedulerName, schedulerId, new DefaultThreadPool(), jobStore);
            var scheduler =  SchedulerRepository.Instance.Lookup(schedulerName).Result;

            scheduler.Clear().Wait();

            var job = JobBuilder.Create<PrintMessageJob>()
                //.WithIdentity("localJob", "default")
                .WithIdentity("localJob")
                .UsingJobData("what","buzhidao")
                .Build();

            var trigger = TriggerBuilder.Create()
                .WithIdentity("trigger1")
                //.WithIdentity("trigger1", "default")
                .ForJob(job)
                .StartNow()
                .WithSimpleSchedule(p=> {
                    p.RepeatForever();
                    p.WithInterval(TimeSpan.FromSeconds(5));
                })
                //.WithCronSchedule("0 /20 * ? * *")
                .Build();

            var offset = scheduler.ScheduleJob(job, trigger).Result;
```
## custom job
```csharp
    public class PrintMessageJob : IJob
    {
        private static readonly Random Random = new Random();

        static int Times = 0;

        public Task Execute(IJobExecutionContext context)
        {
           var mapdata = context.JobDetail.JobDataMap;

            var color = Console.ForegroundColor;
            Console.ForegroundColor = ConsoleColor.DarkYellow;
            Console.WriteLine($"{DateTime.Now.ToLongTimeString()}\tTimes{++Times}\tGreetings from HelloJob!");
            Console.ForegroundColor = color;

            return Task.Delay(TimeSpan.FromSeconds(0));
        }
    }
```

**Comment by lahma** [comment]
You cannot use `new JsonObjectSerializer()` directly, you need to instantiate it as a variable and call `Initialize()` on it. I've updated the code to throw more meaningful exception for this case.
