### ISSUE TITLE
Npgsql.PostgresException: 42883: 操作符不存在

### ISSUE THREAD

**Issue by leoterry-ulrica** [quartznet/quartznet#773]
### Expected behavior
2019-07-01 22:38:35.6710|0|ERROR|Dist.Dme.HSMessage.Consumer.MQ.Kafka.KafkaConsumer|Error: 1/1 brokers are down 
2019-07-01 22:38:35.5994|0|ERROR|Quartz.Impl.AdoJobStore.JobStoreTX|Failure occurred during job recovery: Couldn't recover jobs: 42883: 操作符不存在: character varying = boolean Quartz.JobPersistenceException: Couldn't recover jobs: 42883: 操作符不存在: character varying = boolean ---> Npgsql.PostgresException: 42883: 操作符不存在: character varying = boolean
   at Npgsql.NpgsqlConnector.DoReadMessage(Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isPrependedMessage)
   at Npgsql.NpgsqlConnector.ReadMessage(Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications)
   at Npgsql.NpgsqlConnector.ReadMessage(Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications)
   at Npgsql.NpgsqlConnector.ReadExpecting[T](Boolean async)
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming)
   at Npgsql.NpgsqlDataReader.<NextResultAsync>b__31_0()
   at Npgsql.NpgsqlCommand.Execute(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteDbDataReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.<>c__DisplayClass90_0.<<ExecuteDbDataReaderAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Quartz.Impl.AdoJobStore.StdAdoDelegate.SelectTriggersForRecoveringJobs(ConnectionAndTransactionHolder conn, CancellationToken cancellationToken) in C:\projects\quartznet\src\Quartz\Impl\AdoJobStore\StdAdoDelegate.cs:line 447
   at Quartz.Impl.AdoJobStore.JobStoreSupport.RecoverJobs(ConnectionAndTransactionHolder conn, CancellationToken cancellationToken) in C:\projects\quartznet\src\Quartz\Impl\AdoJobStore\JobStoreSupport.cs:line 665
   --- End of inner exception stack trace ---
   at Quartz.Impl.AdoJobStore.JobStoreSupport.RecoverJobs(ConnectionAndTransactionHolder conn, CancellationToken cancellationToken) in C:\projects\quartznet\src\Quartz\Impl\AdoJobStore\JobStoreSupport.cs:line 697
   at Quartz.Impl.AdoJobStore.JobStoreSupport.<>c__DisplayClass260_0.<<ExecuteInNonManagedTXLock>b__0>d.MoveNext() in C:\projects\quartznet\src\Quartz\Impl\AdoJobStore\JobStoreSupport.cs:line 3729
--- End of stack trace from previous location where exception was thrown ---
   at Quartz.Impl.AdoJobStore.JobStoreSupport.ExecuteInNonManagedTXLock[T](String lockName, Func`2 txCallback, Func`3 txValidator, CancellationToken cancellationToken) in C:\projects\quartznet\src\Quartz\Impl\AdoJobStore\JobStoreSupport.cs:line 3784
   at Quartz.Impl.AdoJobStore.JobStoreSupport.ExecuteInNonManagedTXLock[T](String lockName, Func`2 txCallback, Func`3 txValidator, CancellationToken cancellationToken) in C:\projects\quartznet\src\Quartz\Impl\AdoJobStore\JobStoreSupport.cs:line 3831
   at Quartz.Impl.AdoJobStore.JobStoreSupport.ExecuteInNonManagedTXLock(String lockName, Func`2 txCallback, CancellationToken cancellationToken) in C:\projects\quartznet\src\Quartz\Impl\AdoJobStore\JobStoreSupport.cs:line 3727

**Comment by lahma** [comment]
Need more info, is the DB schema alright?

**Comment by lahma** [comment]
Closing as not enough information provided.
