### ISSUE TITLE
Scheduler stuck

### ISSUE THREAD

**Issue by bhiapp4** [quartznet/quartznet#793]
### Expected behavior
Scheduler should retry when there are temporary database connection issues

### Actual behavior
Scheduler is struck and I have to restart it every time

### Steps to reproduce

```csharp
2019-09-23 07:20:00.0267||DEBUG|Quartz.SQL|Prepared SQL: SELECT TRIGGER_STATE FROM QRTZ_TRIGGERS WHERE SCHED_NAME = 'SalesWorksScheduler' AND TRIGGER_NAME = @triggerName AND TRIGGER_GROUP = @triggerGroup 
2019-09-23 07:20:00.0267||DEBUG|Quartz.SQL|Prepared SQL: SELECT JOB_NAME,JOB_GROUP,DESCRIPTION,JOB_CLASS_NAME,IS_DURABLE,REQUESTS_RECOVERY,JOB_DATA FROM QRTZ_JOB_DETAILS WHERE SCHED_NAME = 'SalesWorksScheduler' AND JOB_NAME = @jobName AND JOB_GROUP = @jobGroup 
2019-09-23 07:20:00.0267||DEBUG|Quartz.SQL|Prepared SQL: UPDATE QRTZ_FIRED_TRIGGERS SET INSTANCE_NAME = @instanceName, FIRED_TIME = @firedTime, SCHED_TIME = @scheduledTime, STATE = @entryState, JOB_NAME = @jobName, JOB_GROUP = @jobGroup, IS_NONCONCURRENT = @isNonConcurrent, REQUESTS_RECOVERY = @requestsRecover WHERE SCHED_NAME = 'SalesWorksScheduler' AND ENTRY_ID = @entryId 
2019-09-23 07:20:00.0267||DEBUG|Quartz.SQL|Prepared SQL: UPDATE QRTZ_TRIGGERS SET TRIGGER_STATE = @state WHERE SCHED_NAME = 'SalesWorksScheduler' AND JOB_NAME = @jobName AND JOB_GROUP = @jobGroup AND TRIGGER_STATE = @oldState 
2019-09-23 07:20:00.0267||DEBUG|Quartz.SQL|Prepared SQL: UPDATE QRTZ_TRIGGERS SET TRIGGER_STATE = @state WHERE SCHED_NAME = 'SalesWorksScheduler' AND JOB_NAME = @jobName AND JOB_GROUP = @jobGroup AND TRIGGER_STATE = @oldState 
2019-09-23 07:20:00.0423||DEBUG|Quartz.SQL|Prepared SQL: UPDATE QRTZ_TRIGGERS SET TRIGGER_STATE = @state WHERE SCHED_NAME = 'SalesWorksScheduler' AND JOB_NAME = @jobName AND JOB_GROUP = @jobGroup AND TRIGGER_STATE = @oldState 
2019-09-23 07:20:00.0423||DEBUG|Quartz.SQL|Prepared SQL: SELECT TRIGGER_NAME FROM QRTZ_TRIGGERS WHERE SCHED_NAME = 'SalesWorksScheduler' AND TRIGGER_NAME = @triggerName AND TRIGGER_GROUP = @triggerGroup 
2019-09-23 07:20:00.0423||DEBUG|Quartz.SQL|Prepared SQL: SELECT TRIGGER_GROUP FROM QRTZ_PAUSED_TRIGGER_GRPS WHERE SCHED_NAME = 'SalesWorksScheduler' AND TRIGGER_GROUP = @triggerGroup 
2019-09-23 07:20:00.0423||DEBUG|Quartz.SQL|Prepared SQL: SELECT TRIGGER_GROUP FROM QRTZ_PAUSED_TRIGGER_GRPS WHERE SCHED_NAME = 'SalesWorksScheduler' AND TRIGGER_GROUP = @triggerGroup 
2019-09-23 07:20:00.0423||DEBUG|Quartz.SQL|Prepared SQL: UPDATE QRTZ_TRIGGERS SET JOB_NAME = @triggerJobName, JOB_GROUP = @triggerJobGroup, DESCRIPTION = @triggerDescription, NEXT_FIRE_TIME = @triggerNextFireTime, PREV_FIRE_TIME = @triggerPreviousFireTime, 
                        TRIGGER_STATE = @triggerState, TRIGGER_TYPE = @triggerType, START_TIME = @triggerStartTime, END_TIME = @triggerEndTime, CALENDAR_NAME = @triggerCalendarName, MISFIRE_INSTR = @triggerMisfireInstruction, PRIORITY = @triggerPriority
                    WHERE SCHED_NAME = 'SalesWorksScheduler' AND TRIGGER_NAME = @triggerName AND TRIGGER_GROUP = @triggerGroup 
2019-09-23 07:20:00.0578||DEBUG|Quartz.SQL|Prepared SQL: UPDATE QRTZ_CRON_TRIGGERS SET CRON_EXPRESSION = @triggerCronExpression, TIME_ZONE_ID = @timeZoneId WHERE SCHED_NAME = 'SalesWorksScheduler' AND TRIGGER_NAME = @triggerName AND TRIGGER_GROUP = @triggerGroup 
2019-09-23 07:20:07.4209||DEBUG|Quartz.Impl.AdoJobStore.MisfireHandler|Scanning for misfires... 
2019-09-23 07:20:07.4209||DEBUG|Quartz.SQL|Prepared SQL: SELECT COUNT(TRIGGER_NAME) FROM QRTZ_TRIGGERS WHERE SCHED_NAME = 'SalesWorksScheduler' AND MISFIRE_INSTR <> -1 AND NEXT_FIRE_TIME < @nextFireTime AND TRIGGER_STATE = @state1 
2019-09-23 07:20:20.0654||ERROR|Quartz.Impl.AdoJobStore.ConnectionAndTransactionHolder|Couldn't rollback ADO.NET connection. Transaction not connected, or was disconnected System.InvalidOperationException: Transaction not connected, or was disconnected
   at Quartz.Impl.AdoJobStore.ConnectionAndTransactionHolder.CheckNotZombied()
   at Quartz.Impl.AdoJobStore.ConnectionAndTransactionHolder.Rollback(Boolean transientError)
2019-09-23 07:20:20.0654||DEBUG|Quartz.Impl.AdoJobStore.SimpleSemaphore|Lock 'TRIGGER_ACCESS' is desired by: 8fe03bce-997b-474c-b8f5-0cbcbfcac89c 
2019-09-23 07:20:20.0654||DEBUG|Quartz.Impl.AdoJobStore.SimpleSemaphore|Lock 'TRIGGER_ACCESS' is being obtained: 8fe03bce-997b-474c-b8f5-0cbcbfcac89c 
2019-09-23 07:20:31.5047||DEBUG|Quartz.Impl.AdoJobStore.JobStoreTX|Found 0 triggers that missed their scheduled fire-time. 
2019-09-23 07:21:07.4232||DEBUG|Quartz.Impl.AdoJobStore.MisfireHandler|Scanning for misfires... 
2019-09-23 07:21:07.4232||DEBUG|Quartz.SQL|Prepared SQL: SELECT COUNT(TRIGGER_NAME) FROM QRTZ_TRIGGERS WHERE SCHED_NAME = 'SalesWorksScheduler' AND MISFIRE_INSTR <> -1 AND NEXT_FIRE_TIME < @nextFireTime AND TRIGGER_STATE = @state1 
2019-09-23 07:21:07.4232||DEBUG|Quartz.Impl.AdoJobStore.JobStoreTX|Found 0 triggers that missed their scheduled fire-time. 

// scheduler and job configuration, SystemTime prefereably set to fixed point
                    ["quartz.serializer.type"] = "json",

                    ["quartz.scheduler.instanceName"] = "SalesWorksScheduler",
                    ["quartz.scheduler.instanceId"] = "instance_one",
                    ["quartz.threadPool.type"] = "Quartz.Simpl.SimpleThreadPool, Quartz",
                    ["quartz.threadPool.threadCount"] = "20",
                    ["quartz.jobStore.misfireThreshold"] = "60000",
                    //["quartz.jobStore.type"] = "Quartz.Simpl.RAMJobStore, Quartz",
                    ["quartz.jobStore.type"] = "Quartz.Impl.AdoJobStore.JobStoreTX, Quartz",
                    //["quartz.jobStore.useProperties"] = "false",
                    ["quartz.jobStore.dataSource"] = "default",
                    //["quartz.jobStore.tablePrefix"] = "QRTZ_",
                    ["quartz.jobStore.driverDelegateType"] = "Quartz.Impl.AdoJobStore.SqlServerDelegate, Quartz",
                    ["quartz.dataSource.default.provider"] = "SqlServer",
                    ["quartz.dataSource.default.connectionString"] = configuration.GetConnectionString("mydbConnection")
 
```

**Comment by martywaz** [comment]
for the configuration above, can you send me a correct sample of the connection string used?  I ran into a similar issue...when the scheduler just got stuck on start.....but I believed my connection string format was correct.

**Comment by martywaz** [comment]
our connection string looks like this:  "Data Source=.;Initial Catalog=MyDatabase;Integrated Security=True"

so....I think the database provider stuff simply doesn't work.

**Comment by martywaz** [comment]
our app.config file looks like below.  maybe some of this is no longer supported in 3.0.7??

<configuration>
  <configSections>
    <section name="quartz" type="System.Configuration.NameValueSectionHandler, System, Version=1.0.5000.0,Culture=neutral, PublicKeyToken=b77a5c561934e089" />
  </configSections>
  <quartz>
    <add key="quartz.dbprovider.ESBSqlServer.productName" value="Microsoft SQL Server" />
    <add key="quartz.dbprovider.ESBSqlServer.assemblyName" value="System.Data, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" />
    <add key="quartz.dbprovider.ESBSqlServer.connectionType" value="System.Data.SqlClient.SqlConnection, System.Data, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" />
    <add key="quartz.dbprovider.ESBSqlServer.commandType" value="System.Data.SqlClient.SqlCommand, System.Data, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" />
    <add key="quartz.dbprovider.ESBSqlServer.parameterType" value="System.Data.SqlClient.SqlParameter, System.Data, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" />
    <add key="quartz.dbprovider.ESBSqlServer.commandBuilderType" value="System.Data.SqlClient.SqlCommandBuilder, System.Data, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" />
    <add key="quartz.dbprovider.ESBSqlServer.parameterDbType" value="System.Data.SqlDbType, System.Data, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" />
    <add key="quartz.dbprovider.ESBSqlServer.parameterDbTypePropertyName" value="SqlDbType" />
    <add key="quartz.dbprovider.ESBSqlServer.parameterNamePrefix" value="@" />
    <add key="quartz.dbprovider.ESBSqlServer.exceptionType" value="System.Data.SqlClient.SqlException, System.Data, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" />
    <add key="quartz.dbprovider.ESBSqlServer.useParameterNamePrefixInParameterCollection" value="true" />
    <add key="quartz.dbprovider.ESBSqlServer.bindByName" value="true" />
    <add key="quartz.dbprovider.ESBSqlServer.dbBinaryTypeName" value="Image" />
  </quartz>
    <startup> 
        <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.7.1" />
    </startup>
</configuration>

**Comment by martywaz** [comment]
ok...got it working

**Comment by lahma** [comment]
Closing as no longer an issue.
