### ISSUE TITLE
Sporadic JobPersistenceException (SerializationException)

### ISSUE THREAD

**Issue by ghost** [quartznet/quartznet#85]
From time to time our application crashes when it retrieves a list of jobs from Quartz.net while a job is executing.

Quartz.JobPersistenceException: Couldn't retrieve job: End of Stream encountered before parsing was completed. ---> System.Runtime.Serialization.SerializationException: End of Stream encountered before parsing was completed.
   at System.Runtime.Serialization.Formatters.Binary.__BinaryParser.Run()
   at System.Runtime.Serialization.Formatters.Binary.ObjectReader.Deserialize(HeaderHandler handler, __BinaryParser serParser, Boolean fCheck, Boolean isCrossAppDomain, IMethodCallMessage methodCallMessage)
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(Stream serializationStream, HeaderHandler handler, Boolean fCheck, Boolean isCrossAppDomain, IMethodCallMessage methodCallMessage)
   at Quartz.Impl.AdoJobStore.StdAdoDelegate.GetObjectFromBlob(IDataReader rs, Int32 colIndex)
   at Quartz.Impl.AdoJobStore.StdAdoDelegate.SelectJobDetail(ConnectionAndTransactionHolder conn, JobKey jobKey, ITypeLoadHelper loadHelper)
   at Quartz.Impl.AdoJobStore.JobStoreSupport.RetrieveJob(ConnectionAndTransactionHolder conn, JobKey jobKey)
   --- End of inner exception stack trace ---
   at Quartz.Impl.AdoJobStore.JobStoreSupport.RetrieveJob(ConnectionAndTransactionHolder conn, JobKey jobKey)
   at Quartz.Impl.AdoJobStore.JobStoreSupport.<>c__DisplayClass19.<RetrieveJob>b__18(ConnectionAndTransactionHolder conn)
   at Quartz.Impl.AdoJobStore.JobStoreSupport.ExecuteInNonManagedTXLock(String lockName, Func`2 txCallback)
   at Quartz.Impl.AdoJobStore.JobStoreTX.ExecuteInLock(String lockName, Func`2 txCallback)
   at Quartz.Impl.AdoJobStore.JobStoreSupport.RetrieveJob(JobKey jobKey)
   at Quartz.Core.QuartzScheduler.GetJobDetail(JobKey jobKey)
   at Quartz.Impl.StdScheduler.GetJobDetail(JobKey jobKey)
...

We are using Sql Server Compact 4.0 (provider SqlServerCe-400) with the AdoJobStore.JobStoreTX.
While trying to fix this problem, I set the lockHandler to UpdateLockRowSemaphore and the driverDelegateType to StdAdoDelegate, with no effect.

When I set the Mode in the connection string to Exclusive, the application crashes after a short time with a sharing violation although there is no other application accessing the database file.

Maybe a separate driver delegate for Sql Server Compact is needed to keep the connection, so that the Mode can be set to Exclusive?
Or is this a multithreading problem?

**Comment by lahma** [comment]
I'm closing this as there's not much that can be done unless somebody has a PR that shows the problem and offers a fix. Microsoft has announced the deprecation of of compact edition so probably should be avoided anyway.
