### ISSUE TITLE
Scheduling failed because Quartz.JobPersistenceException: Failed to obtain DB connection from data source

### ISSUE THREAD

**Issue by SauravGuha** [quartznet/quartznet#853]
Quartz is being used in Service fabric as a statefull service. Every time i redeploy the service , it works for first few request. After that it starts giving the error.
Getting the error when try to
 await scheduler.DeleteJob(this.jobKey, cancellationToken).ConfigureAwait(false);

in NET  Framework version 4.8.0.3761

Quartz version Using version 3.0.7.0

should be able to delete the job.

Longest running query was found to be :
(@lockName nvarchar(14))SELECT * FROM [dbo].QRTZ_LOCKS WITH (UPDLOCK,ROWLOCK) WHERE SCHED_NAME = 'sf-dev-scheduler' AND LOCK_NAME = @lockName

Configuration is from code:

            return new NameValueCollection
            {
                ["quartz.scheduler.instanceName"] = this.GetSectionParameterValue(ConfigurationSectionName, SchedulerName),
                ["quartz.scheduler.instanceId"] = schedulerInstanceId,
                ["quartz.threadPool.type"] = "Quartz.Simpl.SimpleThreadPool, Quartz",
                ["quartz.threadPool.threadCount"] = "10",
                ["quartz.jobStore.misfireThreshold"] = "60000",
                ["quartz.jobStore.type"] = "Quartz.Impl.AdoJobStore.JobStoreTX, Quartz",
                ["quartz.jobStore.useProperties"] = "true",
                ["quartz.jobStore.dataSource"] = "default",
                ["quartz.jobStore.tablePrefix"] = "[dbo].QRTZ_",
                ["quartz.jobStore.clustered"] = "true",
                ["quartz.jobStore.driverDelegateType"] = "Quartz.Impl.AdoJobStore.SqlServerDelegate, Quartz",
                //["quartz.jobStore.lockHandler.type"]= "Quartz.Impl.AdoJobStore.UpdateLockRowSemaphore, Quartz", // If lock failed during transaction we will enable this line
                ["quartz.dataSource.default.connectionString"] = this.GetDBConnectionString(),
                ["quartz.dataSource.default.provider"] = "SqlServer",
                ["quartz.serializer.type"] = "json"
            };

**Comment by lahma** [comment]
Would you mind providing the exact error message and stack trace? Otherwise this is just guesswork.

**Comment by SauravGuha** [comment]
this is the exact stack trace,
Scheduling failed because Quartz.JobPersistenceException: Failed to obtain DB connection from data source 'default': System.InvalidOperationException: Timeout expired.  The timeout period elapsed prior to obtaining a connection from the pool.  This may have occurred because all pooled connections were in use and max pool size was reached.
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at Quartz.Impl.AdoJobStore.JobStoreSupport.GetConnection() ---> System.InvalidOperationException: Timeout expired.  The timeout period elapsed prior to obtaining a connection from the pool.  This may have occurred because all pooled connections were in use and max pool size was reached.
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at Quartz.Impl.AdoJobStore.JobStoreSupport.GetConnection()
   --- End of inner exception stack trace ---
   at Quartz.Impl.AdoJobStore.JobStoreSupport.GetConnection()
   at Quartz.Impl.AdoJobStore.JobStoreSupport.<ExecuteInNonManagedTXLock>d__262`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Quartz.Impl.AdoJobStore.JobStoreSupport.<ExecuteInNonManagedTXLock>d__262`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at APPSeConnect.WebAgent.SchedulerService.V2.Infrastructure.JobScheduler.<DeleteJobIfExistsAsync>d__12.MoveNext() in D:\GitCodeBase\AEC.Platform.Apps\AEC.WebAgent\APPSeConnect.WebAgent.SchedulerService.V2\Infrastructure\JobScheduler.cs:line 74
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at APPSeConnect.WebAgent.SchedulerService.V2.Infrastructure.RequestHandler.<ScheduleProcessflow>d__21.MoveNext() in D:\GitCodeBase\AEC.Platform.Apps\AEC.WebAgent\APPSeConnect.WebAgent.SchedulerService.V2\Infrastructure\RequestHandler.cs:line 346 [See nested exception: System.InvalidOperationException: Timeout expired.  The timeout period elapsed prior to obtaining a connection from the pool.  This may have occurred because all pooled connections were in use and max pool size was reached.
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at Quartz.Impl.AdoJobStore.JobStoreSupport.GetConnection()]

**Comment by lahma** [comment]
If you are running Azure SQL you might be hitting some DTU limits. Try running against dedicated database (for Quartz), adding more resources etc.

**Comment by SauravGuha** [comment]
The Azure SQL DTU for that database is not reached. Can we specify to reuse the connection for quartz ? Or there is no option to do this ?

**Comment by lahma** [comment]
.NET has internal connection pooling. Shouldn't matter here.

**Comment by SauravGuha** [comment]
Ok, let me try to explain the scenario : 
 
I have a service running in multiple partition. So there might be multiple threads operating on the Connection. When I am getting this error, I have checked on Azure SQL, and it seems the DTU For that database instance is below. We have tried to increase the DTU limits, but still facing the same issue. 
 
Can you specify a local settings, which can create one connection from pool and do all operation from there, such that Connection pool max limit is not reached? Or is it not possible. 
 
We can anyway go with local database, but if we can be sure of the actual reason, it will be easier for us to convince my IT guy about the issue.

**Comment by lahma** [comment]
Quartz doesn't manage the connection pool. You can check SQL server connection string's supported properties.

**Comment by SauravGuha** [comment]
Hi,
It seems the issue has been fixed after using a dedicated dbms server. Will keep monitoring it.
Thanks a lot

**Comment by lahma** [comment]
Great that you found a solution!
