### ISSUE TITLE
Mysql8 is not supported？

### ISSUE THREAD

**Issue by 893949088** [quartznet/quartznet#858]
### Version: 3.0.7
 

Connect mysql8 and report the following error：

 Error managing cluster: Failure obtaining db row lock: Table 'quartz.LOCKS' doesn't exist
Quartz.Impl.AdoJobStore.LockException: Failure obtaining db row lock: Table 'quartz.LOCKS' doesn't exist
 ---> MySql.Data.MySqlClient.MySqlException (0x80004005): Table 'quartz.LOCKS' doesn't exist
   at MySql.Data.MySqlClient.MySqlStream.ReadPacket()
   at MySql.Data.MySqlClient.NativeDriver.GetResult(Int32& affectedRow, Int64& insertedId)
   at MySql.Data.MySqlClient.Driver.GetResult(Int32 statementId, Int32& affectedRows, Int64& insertedId)
   at MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)
   at MySql.Data.MySqlClient.MySqlDataReader.NextResult()
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)

**Comment by lahma** [comment]
Fear not MySQL 8 is also supported. Quartz doesn't rely on any specific features of MySQL, just only that you have created the tables.

**Comment by 893949088** [comment]
In the same database structure, mysql5 can connect and run, but mysql8 will report this error.
