### ISSUE TITLE
Possible MySqlConnector bug?

### ISSUE THREAD

**Issue by olicooper** [quartznet/quartznet#902]
### Steps to reproduce

I have quartz options configured with:
```
["quartz.dataSource.ds1.provider"] = "MySqlConnector",
```

I get this error:
```csharp
 ---> Quartz.SchedulerException: Could not Initialize DataSource: ds1
 ---> System.ArgumentException: Error while reading metadata information for provider 'MySqlConnector' (Parameter 'providerName')
 ---> Quartz.SchedulerConfigException: Could not parse property 'connectionType' into correct data type: Could not load type 'MySqlConnector.MySqlConnection' from assembly 'MySqlConnector'.
 ---> System.TypeLoadException: Could not load type 'MySqlConnector.MySqlConnection' from assembly 'MySqlConnector'.
   at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, StackCrawlMarkHandle stackMark, ObjectHandleOnStack assemblyLoadContext, Boolean loadTypeFromPartialName, ObjectHandleOnStack type, ObjectHandleOnStack keepalive)
   at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext, Boolean loadTypeFromPartialName)
   at System.RuntimeType.GetType(String typeName, Boolean throwOnError, Boolean ignoreCase, StackCrawlMark& stackMark)
   at System.Type.GetType(String typeName, Boolean throwOnError)
   at Quartz.Util.ObjectUtils.ConvertValueIfNecessary(Type requiredType, Object newValue)
   at Quartz.Util.ObjectUtils.SetPropertyValue(Object target, String propertyName, Object value)
   at Quartz.Util.ObjectUtils.SetObjectProperties(Object obj, NameValueCollection props)
```

Adding the MySqlConnector v1.0.0 library in manually solved the issue so I think your nuget dependencies need updating?

**Comment by olicooper** [comment]
Ah, this might be due to me already having the `Pomelo.EntityframeworkCore.MySql` package installed which depends on `MySqlConnector` < `1.0.0` which conflicts with the required `MySqlConnector` version >= `1.0.0` for Quartz. This could be an issue for me :/

**Comment by lahma** [comment]
Unfortunately you need to either use earlier beta or 3.0.7. I think one supporting first 1.0  release wins here 😉

**Comment by olicooper** [comment]
Yeah I thought this might be the case. Unfortunately Pomelo are not going to update `MySqlConnector` until their v5.0.0 release  ([see this](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/pull/1103#issuecomment-643736104)) which is likely aligned with .NET 5 release in November 😢 so my project will have to stay on the Quartz beta release for a while longer 👎 What is the latest release I can use?

Anyway, thank you for all your hard work, really excited that v3.1.0 is out! 😄

**Comment by lahma** [comment]
You could probably create a custom provider, via configuration or code: https://github.com/quartznet/quartznet/blob/139aafa23728892b0a5ebf845ce28c3bfdb0bfe8/src/Quartz.Examples/quartz.config , just check VCS history for old dbprovider names.
