### ISSUE TITLE
Quartz.JobPersistenceException: Couldn't acquire next trigger: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by xmaning** [quartznet/quartznet#942]
Hello.

We are getting this error but not in all our jobs, is difficult to catch what is the source of this, but if you could help me to give me any idea of what is probably causing this issue, be appreciated, thanks a lot!

Quartz.JobPersistenceException: Couldn't acquire next trigger: Object reference not set to an instance of an object. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Quartz.Impl.AdoJobStore.JobStoreSupport.<AcquireNextTrigger>d__229.MoveNext()

Version 3.0.7.0

**Comment by lahma** [comment]
This would require the full stack trace with line numbers so that there would be any hope of finding what is happening.

**Comment by xmaning** [comment]
> This would require the full stack trace with line numbers so that there would be any hope of finding what is happening.

Thank you for your answer

This is the entire exception hopefully this could help , thank you!

Quartz.JobPersistenceException: Couldn't acquire next trigger: Object reference not set to an instance of an object. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Quartz.Impl.AdoJobStore.JobStoreSupport.<AcquireNextTrigger>d__229.MoveNext() in C:\projects\quartznet\src\Quartz\Impl\AdoJobStore\JobStoreSupport.cs:line 2637
   --- End of inner exception stack trace ---
   at Quartz.Impl.AdoJobStore.JobStoreSupport.<AcquireNextTrigger>d__229.MoveNext() in C:\projects\quartznet\src\Quartz\Impl\AdoJobStore\JobStoreSupport.cs:line 2688
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Quartz.Impl.AdoJobStore.JobStoreSupport.<ExecuteInNonManagedTXLock>d__262`1.MoveNext() in C:\projects\quartznet\src\Quartz\Impl\AdoJobStore\JobStoreSupport.cs:line 3816
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Quartz.Impl.AdoJobStore.JobStoreSupport.<ExecuteInNonManagedTXLock>d__262`1.MoveNext() in C:\projects\quartznet\src\Quartz\Impl\AdoJobStore\JobStoreSupport.cs:line 3831
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Quartz.Impl.AdoJobStore.JobStoreSupport.<AcquireNextTriggers>d__228.MoveNext() in C:\projects\quartznet\src\Quartz\Impl\AdoJobStore\JobStoreSupport.cs:line 2542
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Quartz.Core.QuartzSchedulerThread.<Run>d__28.MoveNext() in C:\projects\quartznet\src\Quartz\Core\QuartzSchedulerThread.cs:line 262 [See nested exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Quartz.Impl.AdoJobStore.JobStoreSupport.<AcquireNextTrigger>d__229.MoveNext() in C:\projects\quartznet\src\Quartz\Impl\AdoJobStore\JobStoreSupport.cs:line 2637]

**Comment by lahma** [comment]
If you look at the code which is referenced in stack trace:

https://github.com/quartznet/quartznet/blob/e4b4b0c07031afed4779a7b70d2d14ebad8dfbae/src/Quartz/Impl/AdoJobStore/JobStoreSupport.cs#L2637

It looks super odd to job to be missing. Do you have multiple scheduler instances configured as non-clustered against same database or is something else altering the database?

**Comment by xmaning** [comment]
> If you look at the code which is referenced in stack trace:
> 
> https://github.com/quartznet/quartznet/blob/e4b4b0c07031afed4779a7b70d2d14ebad8dfbae/src/Quartz/Impl/AdoJobStore/JobStoreSupport.cs#L2637
> 
> It looks super odd to job to be missing. Do you have multiple scheduler instances configured as non-clustered against same database or is something else altering the database?

Thank you so much for your response, this is our configuration, yes we are using clustering using the same database and nothing else is altering the database. Please let me know if you notice something wrong and sorry for replying late.

properties["quartz.scheduler.instanceName"] = "JobScheduler";
            properties["quartz.scheduler.instanceId"] = Guid.NewGuid().ToString();

            // set thread pool info
            properties["quartz.threadPool.type"] = "Quartz.Simpl.SimpleThreadPool, Quartz";
            properties["quartz.threadPool.threadCount"] =
                string.IsNullOrEmpty(ConfigurationManager.AppSettings.Get("QuartzThreadCount")) ? "10" : ConfigurationManager.AppSettings.Get("QuartzThreadCount");

            properties["quartz.threadPool.threadPriority"] =
                string.IsNullOrEmpty(ConfigurationManager.AppSettings.Get("QuartzThreadPriority")) ? "2" : ConfigurationManager.AppSettings.Get("QuartzThreadPriority");


            #region ADO Data Store Properties

            properties["quartz.jobStore.misfireThreshold"] =
                string.IsNullOrEmpty(ConfigurationManager.AppSettings.Get("QuartzMisfireThreshold")) ? "60000" : ConfigurationManager.AppSettings.Get("QuartzMisfireThreshold");

            properties["quartz.jobStore.maxMisfiresToHandleAtATime"] =
                string.IsNullOrEmpty(ConfigurationManager.AppSettings.Get("QuartzMaxMisfiresToHandleAtATime")) ? "10" : ConfigurationManager.AppSettings.Get("QuartzMaxMisfiresToHandleAtATime");

            properties["quartz.jobStore.useProperties"] = "true";
            properties["quartz.jobStore.type"] = "Quartz.Impl.AdoJobStore.JobStoreTX, Quartz";
            properties["quartz.serializer.type"] = "binary";
            properties["quartz.jobStore.driverDelegateType"] = "Quartz.Impl.AdoJobStore.SqlServerDelegate, Quartz";

            properties["quartz.jobStore.tablePrefix"] = "QRTZ_";
            properties["quartz.jobStore.dataSource"] = "quartzDataSource";
            properties["quartz.dataSource.quartzDataSource.provider"] = "SqlServer";
            //properties["quartz.jobStore.lockHandler.type"] = "Quartz.Impl.AdoJobStore.UpdateLockRowSemaphore, Quartz";
            properties["quartz.jobStore.acquireTriggersWithinLock"] = "true";
            properties["quartz.jobStore.selectWithLockSQL"] = "SELECT * FROM {0}LOCKS WHERE LOCK_NAME=@lockName";

            properties["quartz.jobStore.clustered"] = "true";
            properties["quartz.jobStore.clusterCheckinInterval"] = "20000";

           
            var connectionString = ConfigurationManager.AppSettings.Get("QuartzDatabaseConnectionString");
            if (!string.IsNullOrEmpty(connectionString))
                properties["quartz.dataSource.quartzDataSource.connectionString"] = connectionString;

**Comment by lahma** [comment]
Can't see anything too suspicious in your configuration, you should omit quartz.jobStore.selectWithLockSQL, Quartz will use a better version. Other than that can't really help more advice, just double-check there's no rogue instance running without clustering configuration or anything.
